# Smart MCQ Solver — Final Project Notebook

**Author:** Shruti (22f3002548)  
**Course:** Deep Learning & Generative AI — IIT Madras BS in Data Science  
**Competition:** Smart MCQ Solver Challenge (Kaggle)  
**Metric:** MAP@3 (Mean Average Precision at 3)  
**Target:** ≥ 0.75 MAP@3  
**W&B Project:** `22f3002548-t22026`

### Problem Statement

Given a multiple-choice question with 5 options (A–E), I need to predict the **top 3 most likely correct answers in ranked order**. The evaluation metric is MAP@3 — I score 1.0 if the correct answer is my first prediction, 0.5 if second, 0.333 if third, and 0.0 if not in my top 3.

### My Approach — Progressive Complexity

| Stage | Models | Key Question |
|-------|--------|-------------|
| **EDA** | None | What does my data look like? What should my max_length be? |
| **From Scratch** | TF-IDF+LR, BiLSTM+Attention | How far can I get without pretrained knowledge? |
| **Pretrained** | ELECTRA, DistilRoBERTa, RoBERTa, DeBERTa-v3 | How much does pretrained world knowledge help? |
| **Ensemble** | Optimized blend of transformers | Can combining diverse models push past 0.75? |

### My Key Insight: Sequence Classification > Multiple Choice

Instead of `AutoModelForMultipleChoice` (which scores each option independently in 5 separate inputs), I use `AutoModelForSequenceClassification` with ONE input containing all 5 options. This lets the model:
- See all options simultaneously and compare them through cross-attention
- Use 5× less memory → enabling full fine-tuning instead of LoRA
- Train with larger batch sizes → more stable gradients

### Models Summary

| # | Model | Type | Training Method |
|---|-------|------|----------------|
| 1 | TF-IDF + Logistic Regression | From Scratch | sklearn, no neural weights |
| 2 | BiLSTM + Attention | From Scratch | Custom PyTorch, random init |
| 3 | ELECTRA-base | Pretrained | Full fine-tuning, fp16 |
| 4 | DistilRoBERTa | Pretrained | Full fine-tuning, fp16 |
| 5 | RoBERTa-base | Pretrained | Full fine-tuning, fp16 |
| 6 | DeBERTa-v3-base | Pretrained | Full fine-tuning, NO fp16 |
| 7 | ELECTRA-base (seed 123) | Pretrained | Seed diversity for ensemble |

**GPU Required:** Kaggle → Settings → Accelerator → GPU T4 x2

In [1]:
# ══════════════════════════════════════════════════════════════
# ENVIRONMENT SETUP
# ══════════════════════════════════════════════════════════════

# CRITICAL: Force single GPU to avoid DataParallel crashes with some models
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

# Install required libraries
!pip install accelerate wandb -q

# All imports I need for the entire notebook
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding,
)
from datasets import Dataset as HFDataset
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics.pairwise import cosine_similarity as sklearn_cosine
from sklearn.metrics import precision_recall_fscore_support, accuracy_score
from sklearn.preprocessing import StandardScaler
from scipy.optimize import minimize
from scipy.special import softmax
from collections import Counter
from tqdm import tqdm
import string
import re
import gc
import warnings
warnings.filterwarnings('ignore')

# Verify GPU is available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {device}")
if device.type == 'cuda':
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
else:
    print("WARNING: No GPU! Enable in Settings → Accelerator → GPU T4 x2")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 86.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-cuda 26.2.0 requires cuda-core==0.3.*, but you have cuda-core 1.0.1 which is incompatible.
dask-cuda 26.2.0 requires numba-cuda<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
distributed-ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cuml-cu12 26.2.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cudf-cu12 26.2.1 requires numba-cuda[cu12]<0.23.0,>=0.22.2, but you have numba-cuda 0.30.2 which is incompatible.
Device: cuda
GPU: Tesla T4
Memory: 15.6 GB

## Part 1 — Exploratory Data Analysis

Before I build any model, I need to deeply understand my data. Every decision I make should be **data-informed, not arbitrary**:
- **`max_length`** → determined by text length statistics
- **Train/val split strategy** → determined by answer class balance
- **Model complexity** → determined by question difficulty

In [2]:
# ── Load the competition dataset ───────────────────────────────
train_df = pd.read_csv('/kaggle/input/competitions/smart-mcq-solver-challenge/train.csv')
test_df = pd.read_csv('/kaggle/input/competitions/smart-mcq-solver-challenge/test.csv')

# Constants I use throughout the entire notebook
option_cols = ['A', 'B', 'C', 'D', 'E']
label_to_idx = {'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4}
idx_to_label = {v: k for k, v in label_to_idx.items()}

print(f"Training set: {train_df.shape[0]} questions, {train_df.shape[1]} columns")
print(f"Test set:     {test_df.shape[0]} questions, {test_df.shape[1]} columns")
print(f"Columns: {list(train_df.columns)}")

Training set: 2000 questions, 8 columns
Test set:     500 questions, 7 columns
Columns: ['id', 'prompt', 'A', 'B', 'C', 'D', 'E', 'answer']

### 1.1 Missing Value Check

Missing values in text data would cause tokenization errors or break my feature engineering pipeline. I check both null values and empty strings (which `isnull()` doesn't catch).

In [3]:
# ── Check for nulls ───────────────────────────────────────────
print("Missing values in TRAIN set:")
print(train_df.isnull().sum())
print(f"\nMissing values in TEST set:")
print(test_df.isnull().sum())

# ── Check for empty strings ───────────────────────────────────
for col in ['prompt'] + option_cols:
    empty_train = (train_df[col].astype(str).str.strip() == '').sum()
    empty_test = (test_df[col].astype(str).str.strip() == '').sum()
    if empty_train > 0 or empty_test > 0:
        print(f"WARNING: Empty strings in '{col}': train={empty_train}, test={empty_test}")

print("\nObservation: No missing values or empty strings. My data is clean and complete.")

Missing values in TRAIN set:
id        0
prompt    0
A         0
B         0
C         0
D         0
E         0
answer    0
dtype: int64

Missing values in TEST set:
id        0
prompt    0
A         0
B         0
C         0
D         0
E         0
dtype: int64

Observation: No missing values or empty strings. My data is clean and complete.

### 1.2 Answer Distribution

I need to check if correct answers are balanced across A–E. This matters for three reasons:

1. **Baseline calibration** — a naive "always predict the most common answer" baseline achieves non-trivial MAP@3
2. **Model bias risk** — if 'B' appears 25% but 'E' only 16%, the model might always favor 'B'
3. **Stratified splitting** — random splits might give my validation set very few 'E' answers by chance

In [4]:
# ── Answer frequency counts ───────────────────────────────────
answer_dist = train_df['answer'].value_counts().sort_index()
print("Answer frequency distribution:")
print(answer_dist)

most_freq = answer_dist.idxmax()
least_freq = answer_dist.idxmin()
print(f"\nMost frequent:  {most_freq} ({answer_dist.max()} times, {answer_dist.max()/len(train_df):.1%})")
print(f"Least frequent: {least_freq} ({answer_dist.min()} times, {answer_dist.min()/len(train_df):.1%})")
print(f"Imbalance ratio: {answer_dist.max()/answer_dist.min():.2f}x")

# ── Naive majority-class baseline ──────────────────────────────
# If I always predict the top-3 most frequent answers, what MAP@3 do I get?
top3_labels = answer_dist.sort_values(ascending=False).index[:3].tolist()
naive_scores = []
for _, row in train_df.iterrows():
    if row['answer'] == top3_labels[0]:
        naive_scores.append(1.0)
    elif row['answer'] == top3_labels[1]:
        naive_scores.append(0.5)
    elif row['answer'] == top3_labels[2]:
        naive_scores.append(1/3)
    else:
        naive_scores.append(0.0)

print(f"\nNaive baseline (always predict {top3_labels}): MAP@3 = {np.mean(naive_scores):.4f}")
print(f"→ Any model below this is worse than always guessing the most common answer!")

Answer frequency distribution:
answer
A    369
B    490
C    459
D    358
E    324
Name: count, dtype: int64

Most frequent:  B (490 times, 24.5%)
Least frequent: E (324 times, 16.2%)
Imbalance ratio: 1.51x

Naive baseline (always predict ['B', 'C', 'A']): MAP@3 = 0.4213
→ Any model below this is worse than always guessing the most common answer!

### 1.3 Text Length Analysis

This determines my `max_length` — a critical trade-off:

- **Too short (128):** Text gets truncated, model loses information. With my sequence classification approach (all 5 options in one text), truncation could cut off entire options.
- **Too long (512):** Excessive padding wastes GPU memory. Attention is O(n²), so doubling length quadruples compute.

**My strategy:** I find the 95th percentile of combined (prompt + all options) length, estimate token count, and set `max_length` slightly above. This captures 95%+ of texts while keeping memory manageable. Since I put ALL 5 options in one text, the combined length is much longer than individual prompt-option pairs.

In [5]:
# ── Prompt lengths ─────────────────────────────────────────────
prompt_lens = train_df['prompt'].str.len()
print("PROMPT lengths (characters):")
print(f"  Mean: {prompt_lens.mean():.0f}, Median: {prompt_lens.median():.0f}, Max: {prompt_lens.max()}, 95th: {prompt_lens.quantile(0.95):.0f}")

# ── Option lengths ─────────────────────────────────────────────
print(f"\nOPTION lengths (characters):")
for col in option_cols:
    opt_lens = train_df[col].astype(str).str.len()
    print(f"  {col}: mean={opt_lens.mean():.0f}, max={opt_lens.max()}, 95th={opt_lens.quantile(0.95):.0f}")

# ── Combined length (prompt + ALL options) — this is what my model sees ──
combined_lens = []
for idx in range(len(train_df)):
    row = train_df.iloc[idx]
    # My formatted text includes prompt + all 5 options + labels + instruction
    total = len(str(row['prompt'])) + sum(len(str(row[col])) for col in option_cols) + 100  # ~100 chars for formatting
    combined_lens.append(total)

combined_lens = np.array(combined_lens)
print(f"\nCOMBINED (prompt + ALL options + formatting):")
print(f"  Mean: {combined_lens.mean():.0f}, Median: {np.median(combined_lens):.0f}")
print(f"  Max: {combined_lens.max()}, 95th: {np.percentile(combined_lens, 95):.0f}")

print(f"\nDecision: I'll use max_length=384 tokens. With subword tokenization,")
print(f"most combined texts (~{np.percentile(combined_lens, 95):.0f} chars) fit within 384 tokens.")

PROMPT lengths (characters):
  Mean: 118, Median: 111, Max: 337, 95th: 199

OPTION lengths (characters):
  A: mean=164, max=472, 95th=370
  B: mean=167, max=662, 95th=384
  C: mean=167, max=530, 95th=388
  D: mean=163, max=450, 95th=390
  E: mean=164, max=587, 95th=393

COMBINED (prompt + ALL options + formatting):
  Mean: 1042, Median: 970
  Max: 2703, 95th: 2140

Decision: I'll use max_length=384 tokens. With subword tokenization,
most combined texts (~2140 chars) fit within 384 tokens.

### 1.4 Sample Questions

I look at actual questions to understand what reasoning they require. This tells me whether simple keyword matching will work or if I need deep semantic understanding — directly informing my model selection.

In [6]:
# ── Display sample questions ───────────────────────────────────
for i in [0, 1, 50]:
    row = train_df.iloc[i]
    print(f"\n{'='*60}")
    print(f"Question {i} (ID: {row['id']})")
    print(f"{'='*60}")
    print(f"Prompt: {str(row['prompt'])[:250]}{'...' if len(str(row['prompt'])) > 250 else ''}")
    print()
    for opt in option_cols:
        marker = "  ← CORRECT" if row['answer'] == opt else ""
        print(f"  {opt}: {str(row[opt])[:120]}{'...' if len(str(row[opt])) > 120 else ''}{marker}")

print(f"\n{'='*60}")
print("MY OBSERVATIONS:")
print("  1. Questions require deep conceptual understanding, not keyword matching")
print("  2. Options are lengthy and nuanced — multiple options often sound plausible")
print("  3. Correct answers frequently paraphrase concepts rather than copying prompt words")
print("  4. This justifies using pretrained transformers with world knowledge")
print("  5. Seeing ALL options together helps — the model needs to compare them")

============================================================
Question 0 (ID: 1)
============================================================
Prompt: Pick the best possible answer: What is Martin Heidegger's view on the relationship between time and human existence? among the listed options.

  A: Martin Heidegger believes that humans exist within a time continuum that is infinite and does not have a defined beginni...
  B: Martin Heidegger believes that humans do not exist inside time, but that they are time. The relationship to the past is ...  ← CORRECT
  C: Martin Heidegger does not believe in the existence of time or that it has any effect on human consciousness. The relatio...
  D: Martin Heidegger believes that the relationship between time and human existence is cyclical. The past and present are i...
  E: Martin Heidegger believes that time is an illusion, and the past, present, and future are all happening simultaneously. ...

============================================================
Question 1 (ID: 2)
============================================================
Prompt: What is accelerator-based light-ion fusion?

  A: Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies s...  ← CORRECT
  B: Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies s...
  C: Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies s...
  D: Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies s...
  E: Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies s...

============================================================
Question 50 (ID: 51)
============================================================
Prompt: Which of the following is correct? What is the reason for the stochastic nature of all observed resistance-switching processes? from the following choices.

  A: The free-energy barriers for the transition {i} → {j} are not high enough, and the memory device can switch without havi...
  B: The device is subjected to random thermal fluctuations, which trigger the switching event, but it is impossible to predi...  ← CORRECT
  C: The memory device is found to be in a distinct resistance state {j}, and there exists no physical one-to-one relationshi...
  D: The device is subjected to biases below the threshold value, which still allows for a finite probability of switching, b...
  E: The external bias is set to a value above a certain threshold value, which reduces the free-energy barrier for the trans...

============================================================
MY OBSERVATIONS:
  1. Questions require deep conceptual understanding, not keyword matching
  2. Options are lengthy and nuanced — multiple options often sound plausible
  3. Correct answers frequently paraphrase concepts rather than copying prompt words
  4. This justifies using pretrained transformers with world knowledge
  5. Seeing ALL options together helps — the model needs to compare them

## Part 2 — Utility Functions

I define all my reusable evaluation functions upfront. These are called dozens of times throughout the notebook — once after every model evaluation, inside the ensemble optimizer, and during error analysis.

### MAP@3 — How My Competition Metric Works

For each question, I predict 3 answers in ranked order:
- **Position 1:** score = 1/1 = **1.000** (got it first try)
- **Position 2:** score = 1/2 = **0.500** (correct was my second guess)
- **Position 3:** score = 1/3 = **0.333** (barely caught it)
- **Not in top 3:** score = **0.000** (complete miss)

**MAP@3** = mean of all scores across all questions. To hit 0.75, I need roughly 75% of questions correct at position 1, or a mix like 65% at #1 + 20% at #2.

In [7]:
# ══════════════════════════════════════════════════════════════
# MAP@3 EVALUATION FUNCTIONS
# ══════════════════════════════════════════════════════════════

def ap_at_3(true_label, predicted_labels):
    """
    I score a single question: 1/position if correct answer is in my top 3.
    
    Examples:
        true="A", pred=["A","B","C"] → 1/1 = 1.0   (perfect)
        true="A", pred=["B","A","C"] → 1/2 = 0.5   (found at position 2)
        true="A", pred=["B","C","A"] → 1/3 = 0.333 (found at position 3)
        true="A", pred=["B","C","D"] → 0.0          (not in top 3)
    """
    for i, pred in enumerate(predicted_labels[:3]):
        if pred.strip().upper() == true_label.strip().upper():
            return 1.0 / (i + 1)
    return 0.0


def map_at_3(true_labels, predicted_labels):
    """Mean AP@3 across all questions — my competition metric."""
    return np.mean([ap_at_3(t, p) for t, p in zip(true_labels, predicted_labels)])


def map_at_3_detailed(true_labels, predicted_labels):
    """Full breakdown — I use this for understanding where my model succeeds and fails."""
    scores = [ap_at_3(t, p) for t, p in zip(true_labels, predicted_labels)]
    n = len(scores)
    return {
        'map3': np.mean(scores),
        'correct_at_1': sum(1 for s in scores if s == 1.0),
        'correct_at_2': sum(1 for s in scores if s == 0.5),
        'correct_at_3': sum(1 for s in scores if abs(s - 1/3) < 0.01),
        'missed': sum(1 for s in scores if s == 0.0),
        'total': n,
        'top1_acc': sum(1 for s in scores if s == 1.0) / n,
        'top3_acc': sum(1 for s in scores if s > 0) / n,
    }


def print_results(name, results):
    """Pretty-print so I don't repeat formatting code after every evaluation."""
    print(f"\n{'='*55}")
    print(f"  {name}")
    print(f"{'='*55}")
    print(f"  MAP@3:          {results['map3']:.4f}")
    print(f"  Top-1 Accuracy: {results['top1_acc']:.2%}")
    print(f"  Top-3 Accuracy: {results['top3_acc']:.2%}")
    print(f"  Correct at #1:  {results['correct_at_1']}/{results['total']}")
    print(f"  Correct at #2:  {results['correct_at_2']}/{results['total']}")
    print(f"  Correct at #3:  {results['correct_at_3']}/{results['total']}")
    print(f"  Missed:         {results['missed']}/{results['total']}")


def logits_to_preds(logits):
    """
    I convert (N, 5) scores to top-3 label predictions.
    Used after every model's inference and inside the ensemble.
    """
    preds = []
    for i in range(len(logits)):
        top3_indices = np.argsort(logits[i])[::-1][:3]
        preds.append([idx_to_label[idx] for idx in top3_indices])
    return preds


def clean_text(text):
    """Basic cleaning for my scratch models' feature engineering."""
    if pd.isna(text):
        return ""
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text


# I'll store every model's results here for the final comparison
all_results = {}

print("All utility functions ready.")

All utility functions ready.

## Part 3 — W&B Setup

I connect to Weights & Biases for experiment tracking. Every model gets logged as a separate run so I can compare them on a single dashboard. The examiners will review this during viva.

In [8]:
import wandb
from kaggle_secrets import UserSecretsClient
secrets = UserSecretsClient()
wandb.login(key=secrets.get_secret("WANDB_API_KEY"))

PROJECT_NAME = "22f3002548-t22026"
print(f"W&B login successful! Project: {PROJECT_NAME}")

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: [wandb.login()] Using explicit session credentials for https://api.wandb.ai.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

W&B login successful! Project: 22f3002548-t22026

## Part 4 — Feature Engineering

I compute handcrafted features for my scratch models. These capture surface-level text patterns that correlate with correctness.

**Important:** These features are ONLY for my scratch models. The transformers learn their own features from raw text and ignore these completely.

### My 6 Features

| Feature | Intuition |
|---------|-----------|
| **TF-IDF cosine similarity** | Important words shared between prompt and option |
| **Word overlap ratio** | Raw vocabulary overlap |
| **Option word count** | Correct answers might be longer (more detailed) |
| **Prompt word count** | Context for computing length ratio |
| **Length ratio** | Extreme ratios (very short/long answers) may indicate distractors |
| **Unique option words** | Correct answers often introduce specific factual terms |

### The Ceiling of Handcrafted Features

No matter how clever, these features can't capture word order, paraphrasing, multi-step reasoning, or world knowledge. That's why I need pretrained transformers.

In [9]:
def compute_features(df, tfidf_vectorizer=None, fit=False):
    """
    I compute 6 features for every (prompt, option) pair.
    Returns: (N, 5, 6) feature matrix and the fitted vectorizer.
    """
    all_text = df['prompt'].apply(clean_text).tolist()
    for col in option_cols:
        all_text.extend(df[col].astype(str).apply(clean_text).tolist())
    
    if fit:
        tfidf_vectorizer = TfidfVectorizer(
            max_features=20000, ngram_range=(1, 2),
            stop_words='english', sublinear_tf=True
        )
        tfidf_vectorizer.fit(all_text)
        print(f"  TF-IDF fitted: {len(tfidf_vectorizer.vocabulary_)} features")
    
    features_list = []
    for idx in range(len(df)):
        row = df.iloc[idx]
        prompt_clean = clean_text(row['prompt'])
        prompt_words = set(prompt_clean.split())
        prompt_vec = tfidf_vectorizer.transform([prompt_clean])
        
        row_features = []
        for col in option_cols:
            opt_clean = clean_text(row[col])
            opt_words = set(opt_clean.split())
            opt_vec = tfidf_vectorizer.transform([opt_clean])
            
            cos_sim = sklearn_cosine(prompt_vec, opt_vec)[0][0]
            overlap = len(prompt_words & opt_words) / max(len(prompt_words | opt_words), 1)
            opt_len = len(opt_clean.split()) / 100
            prompt_len = len(prompt_clean.split()) / 100
            len_ratio = len(opt_clean.split()) / max(len(prompt_clean.split()), 1)
            unique_frac = len(opt_words - prompt_words) / max(len(opt_words), 1)
            
            row_features.append([cos_sim, overlap, opt_len, prompt_len, len_ratio, unique_frac])
        features_list.append(row_features)
    
    return np.array(features_list), tfidf_vectorizer

print("Computing features...")
train_features, tfidf_vec = compute_features(train_df, fit=True)
test_features, _ = compute_features(test_df, tfidf_vectorizer=tfidf_vec)
print(f"Feature shapes: train={train_features.shape}, test={test_features.shape}")

Computing features...
  TF-IDF fitted: 10876 features
Feature shapes: train=(2000, 5, 6), test=(500, 5, 6)

## Part 5 — Model 1: TF-IDF + Logistic Regression (From Scratch)

My first "model built from scratch" — NO pretrained neural network weights. This satisfies the project requirement.

### How TF-IDF Works (For My Viva)

**TF (Term Frequency):** How often a word appears in this text. "Mitochondria" appearing 3 times → high TF.

**IDF (Inverse Document Frequency):** How rare the word is across ALL texts. "The" is everywhere → low IDF. "Mitochondria" is rare → high IDF.

**TF-IDF = TF × IDF:** Words that are frequent HERE but rare OVERALL get highest weight. This makes domain-specific terms more important than common words.

### My Classification Approach

I frame MCQ solving as **binary classification**: for each (prompt, option) pair, predict P(correct).
- 2000 questions × 5 options = 10,000 training examples
- Only 2000 are positive → 4:1 class imbalance
- I use `class_weight='balanced'` to upweight the minority class

Logistic Regression is fully transparent — I can inspect coefficients to see which features matter most. It's the simplest classifier, making it a true "from scratch" approach.

In [10]:
# ── Reshape for binary classification ──────────────────────────
# (2000, 5, 6) → (10000, 6) — treat each option independently
X_train_flat = train_features.reshape(-1, train_features.shape[-1])

# Labels: 1 if correct, 0 if wrong (only 20% are positive)
y_train_flat = []
for idx, row in train_df.iterrows():
    for col in option_cols:
        y_train_flat.append(1 if row['answer'] == col else 0)
y_train_flat = np.array(y_train_flat)

print(f"Training data: {X_train_flat.shape}")
print(f"Positive: {y_train_flat.sum()}/{len(y_train_flat)} ({y_train_flat.mean():.1%})")

# ── Scale and train ────────────────────────────────────────────
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_flat)

lr_model = LogisticRegression(max_iter=1000, class_weight='balanced', C=1.0)
lr_model.fit(X_train_scaled, y_train_flat)

# ── Get scores ─────────────────────────────────────────────────
lr_train_scores = lr_model.predict_proba(X_train_scaled)[:, 1].reshape(len(train_df), 5)
X_test_scaled = scaler.transform(test_features.reshape(-1, test_features.shape[-1]))
lr_test_scores = lr_model.predict_proba(X_test_scaled)[:, 1].reshape(len(test_df), 5)

# ── Evaluate ───────────────────────────────────────────────────
lr_preds = logits_to_preds(lr_train_scores)
results_lr = map_at_3_detailed(train_df['answer'].tolist(), lr_preds)
print_results("Model 1: TF-IDF + Logistic Regression (from scratch)", results_lr)
all_results['TF-IDF + LR'] = results_lr

# ── Feature importance ─────────────────────────────────────────
feature_names = ['TF-IDF Cosine', 'Word Overlap', 'Opt Length', 'Prompt Length', 'Length Ratio', 'Unique Words']
print(f"\nFeature importance (LR coefficients):")
for name, coef in sorted(zip(feature_names, lr_model.coef_[0]), key=lambda x: abs(x[1]), reverse=True):
    print(f"  {name:>14}: {coef:+.3f}")

Training data: (10000, 6)
Positive: 2000/10000 (20.0%)

=======================================================
  Model 1: TF-IDF + Logistic Regression (from scratch)
=======================================================
  MAP@3:          0.5603
  Top-1 Accuracy: 37.10%
  Top-3 Accuracy: 81.15%
  Correct at #1:  742/2000
  Correct at #2:  510/2000
  Correct at #3:  371/2000
  Missed:         377/2000

Feature importance (LR coefficients):
    Unique Words: +0.217
      Opt Length: +0.094
   Prompt Length: +0.078
    Length Ratio: +0.066
   TF-IDF Cosine: +0.052
    Word Overlap: +0.004

## Part 6 — Model 2: BiLSTM with Attention (From Scratch)

My second scratch model where **every parameter is randomly initialized** and learned from our 2000-question dataset. No pretrained word vectors, no pretrained encoders.

### Architecture Deep Dive (For My Viva)

**Embedding Layer:** I build a custom vocabulary from training data. Each word maps to a learnable 128-dim vector. Unlike GloVe, these start random and train end-to-end.

**Bidirectional LSTM:** Processes text sequentially with two passes:
- Forward: reads left-to-right, captures past context
- Backward: reads right-to-left, captures future context
- LSTMs use gates (forget, input, output) to control information flow, solving the vanishing gradient problem that kills standard RNNs.

### Attention & Classification

**Custom Attention:** Not all words matter equally. My attention layer learns:

weight(word) = softmax(Linear(LSTM_output(word)))
context = Σ weight(word) × LSTM_output(word)

This emphasizes relevant words (e.g., "mitochondria") while ignoring filler ("the", "is").

**Shared Encoder:** The same LSTM+Attention processes all 5 (prompt+option) pairs. This treats all options fairly and prevents overfitting with only 2000 examples.

**Expected limitation:** Tiny vocabulary (~3K words), no pretrained knowledge. The model can't "know" that mitochondria produce ATP.

In [11]:
# ══════════════════════════════════════════════════════════════
# STEP 1: Build custom vocabulary from training data
# ══════════════════════════════════════════════════════════════

SPECIAL_TOKENS = {"<PAD>": 0, "<UNK>": 1}
counter = Counter()

# I count word frequencies across all prompts and options
for _, row in train_df.iterrows():
    for col in ['prompt'] + option_cols:
        words = clean_text(row[col]).split()
        counter.update(words)

# Build vocab: special tokens + all words with frequency ≥ 2
vocab = dict(SPECIAL_TOKENS)
for word, count in counter.items():
    if count >= 2:  # skip very rare words
        vocab[word] = len(vocab)

print(f"Vocabulary size: {len(vocab)} words (from {len(counter)} unique tokens)")
print(f"Special tokens: <PAD>=0, <UNK>=1")


# ══════════════════════════════════════════════════════════════
# STEP 2: Custom tokenizer
# ══════════════════════════════════════════════════════════════

SCRATCH_MAX_LENGTH = 128

def scratch_tokenize(text):
    """My custom tokenizer: clean → split → vocab lookup → pad/truncate."""
    words = clean_text(text).split()
    tokens = [vocab.get(word, vocab["<UNK>"]) for word in words]
    tokens = tokens[:SCRATCH_MAX_LENGTH]                          # truncate
    tokens += [vocab["<PAD>"]] * (SCRATCH_MAX_LENGTH - len(tokens))  # pad
    return tokens


# ══════════════════════════════════════════════════════════════
# STEP 3: Dataset class
# ══════════════════════════════════════════════════════════════

class ScratchMCQDataset(Dataset):
    """Each question becomes 5 tokenized (prompt + option) sequences."""
    def __init__(self, dataframe, is_train=True):
        self.df = dataframe.reset_index(drop=True)
        self.is_train = is_train
    
    def __len__(self):
        return len(self.df)
    
    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        
        # Create 5 sequences: prompt concatenated with each option
        sequences = []
        for col in option_cols:
            text = str(row['prompt']) + " " + str(row[col])
            sequences.append(scratch_tokenize(text))
        
        sequences = torch.tensor(sequences, dtype=torch.long)  # (5, 128)
        
        if self.is_train:
            label = torch.tensor(label_to_idx[row['answer']], dtype=torch.long)
            return sequences, label
        return sequences


# ══════════════════════════════════════════════════════════════
# STEP 4: Attention mechanism
# ══════════════════════════════════════════════════════════════

class Attention(nn.Module):
    """
    My custom attention: learns a scoring function over LSTM hidden states.
    Produces a weighted sum of states, focusing on the most relevant words.
    """
    def __init__(self, hidden_size):
        super().__init__()
        self.attention = nn.Linear(hidden_size * 2, 1)  # *2 because bidirectional LSTM
    
    def forward(self, lstm_output):
        # lstm_output: (batch, seq_len, hidden_size*2)
        scores = self.attention(lstm_output)             # (batch, seq_len, 1)
        weights = torch.softmax(scores, dim=1)           # normalize across sequence
        context = torch.sum(weights * lstm_output, dim=1) # weighted sum → (batch, hidden_size*2)
        return context


# ══════════════════════════════════════════════════════════════
# STEP 5: BiLSTM + Attention model
# ══════════════════════════════════════════════════════════════

class BiLSTMAttentionMCQ(nn.Module):
    """
    My from-scratch model architecture:
    Embedding → BiLSTM → Attention → FC → Score per option
    """
    def __init__(self, vocab_size, embedding_dim=128, hidden_size=128, dropout=0.3):
        super().__init__()
        
        # Learned embeddings (NOT pretrained)
        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)
        
        # Bidirectional LSTM — processes text forward AND backward
        self.lstm = nn.LSTM(embedding_dim, hidden_size, batch_first=True, bidirectional=True)
        
        # My custom attention mechanism
        self.attention = Attention(hidden_size)
        
        self.dropout = nn.Dropout(dropout)
        
        # Final scoring layers
        self.fc = nn.Sequential(
            nn.Linear(hidden_size * 2, 128),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(128, 1),  # one score per option
        )
    
    def forward(self, x):
        # x: (batch, 5, seq_len)
        batch_size = x.size(0)
        
        # Reshape: process all 5 options as separate sequences
        x = x.view(batch_size * 5, SCRATCH_MAX_LENGTH)  # (batch*5, 128)
        
        x = self.embedding(x)                             # (batch*5, 128, embed_dim)
        lstm_out, _ = self.lstm(x)                         # (batch*5, 128, hidden*2)
        context = self.attention(lstm_out)                  # (batch*5, hidden*2)
        context = self.dropout(context)
        scores = self.fc(context)                          # (batch*5, 1)
        
        # Reshape back: one score per option per question
        scores = scores.view(batch_size, 5)                # (batch, 5)
        return scores


print("BiLSTM + Attention model defined.")

Vocabulary size: 2972 words (from 2973 unique tokens)
Special tokens: <PAD>=0, <UNK>=1
BiLSTM + Attention model defined.

### 6.1 Training the BiLSTM Model

I train with CrossEntropyLoss (the correct option should have the highest score), Adam optimizer, and a learning rate scheduler that reduces LR when validation accuracy plateaus. I save the best checkpoint and use early stopping.

In [12]:
# ── Train/val split ────────────────────────────────────────────
scratch_train_data, scratch_val_data = train_test_split(
    train_df, test_size=0.10, random_state=42, stratify=train_df['answer']
)

train_dataset_s = ScratchMCQDataset(scratch_train_data, is_train=True)
val_dataset_s = ScratchMCQDataset(scratch_val_data, is_train=True)

train_loader_s = DataLoader(train_dataset_s, batch_size=32, shuffle=True)
val_loader_s = DataLoader(val_dataset_s, batch_size=32, shuffle=False)

# ── Initialize model ──────────────────────────────────────────
scratch_model = BiLSTMAttentionMCQ(vocab_size=len(vocab)).to(device)
optimizer_s = optim.AdamW(scratch_model.parameters(), lr=1e-3, weight_decay=1e-4)
criterion_s = nn.CrossEntropyLoss()
scheduler_s = optim.lr_scheduler.ReduceLROnPlateau(optimizer_s, mode='max', factor=0.5, patience=2)

total_params = sum(p.numel() for p in scratch_model.parameters())
print(f"BiLSTM + Attention — {total_params:,} parameters (all learned from scratch)")
print(f"Train: {len(train_dataset_s)}, Val: {len(val_dataset_s)}\n")

# ── Training loop ─────────────────────────────────────────────
best_val_acc = 0
best_state = None
patience_counter = 0
EPOCHS = 15

for epoch in range(EPOCHS):
    # Train
    scratch_model.train()
    total_loss = 0
    for inputs, labels in train_loader_s:
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer_s.zero_grad()
        outputs = scratch_model(inputs)
        loss = criterion_s(outputs, labels)
        loss.backward()
        optimizer_s.step()
        total_loss += loss.item()
    
    # Validate
    scratch_model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for inputs, labels in val_loader_s:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = scratch_model(inputs)
            preds = outputs.argmax(dim=1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)
    
    val_acc = correct / total
    scheduler_s.step(val_acc)
    
    print(f"  Epoch {epoch+1}/{EPOCHS}: loss={total_loss/len(train_loader_s):.4f}, val_acc={val_acc:.4f}, lr={optimizer_s.param_groups[0]['lr']:.6f}")
    
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        best_state = {k: v.clone() for k, v in scratch_model.state_dict().items()}
        patience_counter = 0
    else:
        patience_counter += 1
    
    if patience_counter >= 5:
        print(f"  Early stopping at epoch {epoch+1}")
        break

print(f"\nBest validation accuracy: {best_val_acc:.4f}")

# ── Load best model and get predictions ────────────────────────
scratch_model.load_state_dict(best_state)
scratch_model.eval()

# Predict on full training set
full_train_ds = ScratchMCQDataset(train_df, is_train=False)
full_train_loader = DataLoader(full_train_ds, batch_size=32, shuffle=False)
all_logits = []
with torch.no_grad():
    for inputs in full_train_loader:
        inputs = inputs.to(device)
        outputs = scratch_model(inputs)
        all_logits.append(outputs.cpu().numpy())
scratch_train_logits = np.concatenate(all_logits, axis=0)

# Predict on test set
test_ds_s = ScratchMCQDataset(test_df, is_train=False)
test_loader_s = DataLoader(test_ds_s, batch_size=32, shuffle=False)
all_logits = []
with torch.no_grad():
    for inputs in test_loader_s:
        inputs = inputs.to(device)
        outputs = scratch_model(inputs)
        all_logits.append(outputs.cpu().numpy())
scratch_test_logits = np.concatenate(all_logits, axis=0)

# Evaluate
scratch_preds = logits_to_preds(scratch_train_logits)
results_scratch = map_at_3_detailed(train_df['answer'].tolist(), scratch_preds)
print_results("Model 2: BiLSTM + Attention (from scratch)", results_scratch)
all_results['BiLSTM + Attn'] = results_scratch

# Free memory
del scratch_model
gc.collect()
torch.cuda.empty_cache()

BiLSTM + Attention — 677,890 parameters (all learned from scratch)
Train: 1800, Val: 200

  Epoch 1/15: loss=1.5221, val_acc=0.5700, lr=0.001000
  Epoch 2/15: loss=0.7971, val_acc=0.8600, lr=0.001000
  Epoch 3/15: loss=0.2711, val_acc=0.9750, lr=0.001000
  Epoch 4/15: loss=0.0743, val_acc=0.9850, lr=0.001000
  Epoch 5/15: loss=0.0499, val_acc=1.0000, lr=0.001000
  Epoch 6/15: loss=0.0123, val_acc=1.0000, lr=0.001000
  Epoch 7/15: loss=0.0183, val_acc=1.0000, lr=0.001000
  Epoch 8/15: loss=0.0305, val_acc=1.0000, lr=0.000500
  Epoch 9/15: loss=0.0040, val_acc=1.0000, lr=0.000500
  Epoch 10/15: loss=0.0011, val_acc=1.0000, lr=0.000500
  Early stopping at epoch 10

Best validation accuracy: 1.0000

=======================================================
  Model 2: BiLSTM + Attention (from scratch)
=======================================================
  MAP@3:          1.0000
  Top-1 Accuracy: 100.00%
  Top-3 Accuracy: 100.00%
  Correct at #1:  2000/2000
  Correct at #2:  0/2000
  Correct at #3:  0/2000
  Missed:         0/2000

## Part 7 — Transformer Fine-Tuning: My Sequence Classification Approach

### The Core Insight

Instead of `AutoModelForMultipleChoice` (which creates 5 separate inputs and scores each option independently), I use `AutoModelForSequenceClassification` with `num_labels=5`. I format each question as ONE text string containing the prompt AND all 5 options:

Question:
What is Heidegger's view on time?

Options:
A. Humans exist within infinite time...
B. Humans do not exist inside time, but they are time...
C. Time has no effect...
D. The relationship is cyclical...
E. Time is an illusion...

Choose the correct answer.

The model reads this entire text and classifies it into one of 5 classes (A=0 through E=4).

### Why This Is Better
1. **Cross-option attention** — the model sees all options together and can compare them
2. **5× less memory** — one input per question instead of five → enables full fine-tuning
3. **Larger batches** — `batch_size=8` with `fp16=True` (vs batch_size=2 without fp16)
4. **Full fine-tuning** — ALL parameters are trained, not just LoRA adapters (~1%)

### Why Sequence Classification Beats Multiple Choice

| Aspect | Multiple Choice | Sequence Classification |
|--------|----------------|----------------------|
| Inputs per question | 5 separate sequences | 1 combined sequence |
| Can model compare options? | No — each scored independently | Yes — cross-attention across all options |
| GPU memory per question | 5× | 1× |
| Max batch size (T4) | 2–4 | 8–16 |
| Fine-tuning method | LoRA only (~1% params) | Full (~100% params) |

The model can now learn patterns like "options B and D contradict each other, so one is likely correct" — impossible with multiple choice.

### What Is Fine-Tuning?

**Pretraining:** Model trained on billions of words to learn general language understanding (weeks, hundreds of GPUs).

**Fine-tuning:** I continue training on my 2000-question MCQ dataset (minutes, one GPU).

**Analogy:** Pretraining = university education. Fine-tuning = job-specific training course. You don't re-learn English — you learn to apply existing knowledge to the new task.

### Training Hyperparameters

| Parameter | Value | Why |
|-----------|-------|-----|
| `learning_rate=2e-5` | Too high → catastrophic forgetting. Too low → doesn't learn. |
| `epochs=5` | Enough to converge. More risks overfitting. |
| `warmup_steps=100` | Prevents random classification head from damaging pretrained weights |
| `weight_decay=0.01` | L2 regularization to reduce overfitting |
| `max_length=384` | Captures 95%+ of formatted texts |
| `fp16=True` | Halves memory. EXCEPT DeBERTa-v3 which crashes. |

In [13]:
# ══════════════════════════════════════════════════════════════
# TEXT FORMATTING — all options in one string
# ══════════════════════════════════════════════════════════════

def prepare_text(row):
    """
    I format each question as a single string containing the prompt
    and ALL 5 options. The model sees everything in one forward pass.
    """
    return (
        f"Question:\n{row['prompt']}\n\n"
        f"Options:\n"
        f"A. {row['A']}\n"
        f"B. {row['B']}\n"
        f"C. {row['C']}\n"
        f"D. {row['D']}\n"
        f"E. {row['E']}\n\n"
        f"Choose the correct answer."
    )

# Add formatted text and numeric labels to both dataframes
train_df['text'] = train_df.apply(prepare_text, axis=1)
test_df['text'] = test_df.apply(prepare_text, axis=1)
train_df['label'] = train_df['answer'].map(label_to_idx)

# Verify
print("Sample formatted text:")
print("=" * 60)
print(train_df['text'].iloc[0][:400])
print("=" * 60)
print(f"\nLabel: {train_df['label'].iloc[0]} ({train_df['answer'].iloc[0]})")
print(f"Text lengths — mean: {train_df['text'].str.len().mean():.0f}, max: {train_df['text'].str.len().max()}")

Sample formatted text:
============================================================
Question:
Pick the best possible answer: What is Martin Heidegger's view on the relationship between time and human existence? among the listed options.

Options:
A. Martin Heidegger believes that humans exist within a time continuum that is infinite and does not have a defined beginning or end. The relationship to the past involves acknowledging it as a historical era, and the relationship to the
============================================================

Label: 1 (B)
Text lengths — mean: 1010, max: 2671

### 7.1 Master Training Function

This single function handles everything for any transformer model. I call it once per model, just changing the model name. It:
1. Splits data (stratified 90/10)
2. Loads tokenizer and model
3. Tokenizes all texts
4. Trains with early stopping based on F1
5. Predicts on full train + test → returns logits
6. Cleans up GPU memory

In [14]:
def train_and_predict(
    model_name, train_df, test_df,
    max_length=384, learning_rate=2e-5, batch_size=8,
    epochs=5, seed=42, run_name="model", use_fp16=True,
):
    """
    My complete pipeline: load → fine-tune → predict → cleanup.
    Uses AutoModelForSequenceClassification (5-class) with full fine-tuning.
    """
    print(f"\n{'='*60}")
    print(f"  TRAINING: {run_name}")
    print(f"  Model: {model_name}")
    print(f"  lr={learning_rate}, max_len={max_length}, batch={batch_size}, epochs={epochs}")
    print(f"  Fine-tuning: FULL (all parameters), fp16={use_fp16}")
    print(f"{'='*60}")
    
    # ── Split ──────────────────────────────────────────────────
    tr_data, val_data = train_test_split(
        train_df, test_size=0.10, random_state=seed, stratify=train_df['label']
    )
    tr_data = tr_data.reset_index(drop=True)
    val_data = val_data.reset_index(drop=True)
    print(f"  Split: {len(tr_data)} train, {len(val_data)} val")
    
    # ── HuggingFace datasets ───────────────────────────────────
    train_ds = HFDataset.from_pandas(tr_data[['text', 'label']])
    val_ds = HFDataset.from_pandas(val_data[['text', 'label']])
    test_ds = HFDataset.from_pandas(test_df[['text']])
    full_train_ds = HFDataset.from_pandas(train_df[['text', 'label']])
    
    # ── Load model ─────────────────────────────────────────────
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name, num_labels=5, id2label=idx_to_label, label2id=label_to_idx,
    ).to(device)
    
    total_params = sum(p.numel() for p in model.parameters())
    print(f"  Parameters: {total_params:,} (ALL trainable)")
    
    # ── Tokenize ───────────────────────────────────────────────
    def tok_fn(examples):
        return tokenizer(examples['text'], truncation=True, max_length=max_length)
    
    train_ds = train_ds.map(tok_fn, batched=True, remove_columns=['text'])
    val_ds = val_ds.map(tok_fn, batched=True, remove_columns=['text'])
    test_ds = test_ds.map(tok_fn, batched=True, remove_columns=['text'])
    full_train_ds = full_train_ds.map(tok_fn, batched=True, remove_columns=['text'])
    
    collator = DataCollatorWithPadding(tokenizer=tokenizer)
    
    # ── Metrics ────────────────────────────────────────────────
    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        predictions = np.argmax(logits, axis=-1)
        prec, rec, f1, _ = precision_recall_fscore_support(labels, predictions, average='weighted', zero_division=0)
        acc = accuracy_score(labels, predictions)
        
        pred_labels = [[idx_to_label[idx] for idx in np.argsort(logits[i])[::-1][:3]] for i in range(len(labels))]
        true_labels = [idx_to_label[l] for l in labels]
        m3 = map_at_3(true_labels, pred_labels)
        
        return {'accuracy': acc, 'f1': f1, 'map3': m3}
    
    # ── Training args ──────────────────────────────────────────
    args = TrainingArguments(
        output_dir=f'./output_{run_name}',
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        greater_is_better=True,
        learning_rate=learning_rate,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        num_train_epochs=epochs,
        weight_decay=0.01,
        warmup_steps=100,
        logging_steps=50,
        save_total_limit=1,
        fp16=use_fp16 and torch.cuda.is_available(),
        report_to="none",
        seed=seed,
    )
    
    # ── Train ──────────────────────────────────────────────────
    trainer = Trainer(
        model=model, args=args,
        train_dataset=train_ds, eval_dataset=val_ds,
        data_collator=collator, compute_metrics=compute_metrics,
    )
    
    trainer.train()
    
    val_metrics = trainer.evaluate()
    print(f"\n  Val: acc={val_metrics['eval_accuracy']:.4f}, f1={val_metrics['eval_f1']:.4f}, map3={val_metrics['eval_map3']:.4f}")
    
    # ── Predict ────────────────────────────────────────────────
    print("  Predicting on full train + test...")
    train_logits = trainer.predict(full_train_ds).predictions
    test_logits = trainer.predict(test_ds).predictions
    
    # ── Cleanup ────────────────────────────────────────────────
    del model, trainer
    gc.collect()
    torch.cuda.empty_cache()
    print(f"  ✓ Done. GPU cleared.")
    
    return train_logits, test_logits, val_metrics


print("Training function ready.")

Training function ready.

## Part 8 — Model 3: ELECTRA-base (Full Fine-tuning)

### How ELECTRA Differs From BERT

**BERT** masks 15% of tokens and predicts them → learns from only 15% of input.

**ELECTRA** replaces some tokens with plausible alternatives and the discriminator detects which tokens are fake → learns from **100% of tokens** (6.7× more signal per example).

This makes ELECTRA significantly more sample-efficient — critical for my small 2000-question dataset.

### Why I Expect ELECTRA To Be Strong

1. **Sample efficiency** — extracts maximum learning from each of my 2000 examples
2. **Discriminative training** — detecting real vs fake tokens aligns with MCQ solving (correct vs incorrect options)
3. **fp16 compatible** — enables batch_size=8 for fast training
4. I use `google/electra-base-discriminator` — the discriminator component (generator is discarded after pretraining)

In [15]:
logits_train_electra, logits_test_electra, metrics_electra = train_and_predict(
    model_name="google/electra-base-discriminator",
    train_df=train_df, test_df=test_df,
    max_length=384, learning_rate=2e-5, batch_size=8,
    epochs=5, seed=42, run_name="electra_base", use_fp16=True,
)

preds_electra = logits_to_preds(logits_train_electra)
results_electra = map_at_3_detailed(train_df['answer'].tolist(), preds_electra)
print_results("Model 3: ELECTRA (full fine-tuning)", results_electra)
all_results['ELECTRA'] = results_electra

============================================================
  TRAINING: electra_base
  Model: google/electra-base-discriminator
  lr=2e-05, max_len=384, batch=8, epochs=5
  Fine-tuning: FULL (all parameters), fp16=True
============================================================
  Split: 1800 train, 200 val

config.json:   0%|          | 0.00/666 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: google/electra-base-discriminator
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.weight            | UNEXPECTED |
electra.embeddings_project.weight                 | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings_project.bias                   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.dense.weight                           | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

  Parameters: 109,486,085 (ALL trainable)

Map:   0%|          | 0/1800 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['electra.embeddings.LayerNorm.weight', 'electra.embeddings.LayerNorm.bias', 'electra.encoder.layer.0.attention.output.LayerNorm.weight', 'electra.encoder.layer.0.attention.output.LayerNorm.bias', 'electra.encoder.layer.0.output.LayerNorm.weight', 'electra.encoder.layer.0.output.LayerNorm.bias', 'electra.encoder.layer.1.attention.output.LayerNorm.weight', 'electra.encoder.layer.1.attention.output.LayerNorm.bias', 'electra.encoder.layer.1.output.LayerNorm.weight', 'electra.encoder.layer.1.output.LayerNorm.bias', 'electra.encoder.layer.2.attention.output.LayerNorm.weight', 'electra.encoder.layer.2.attention.output.LayerNorm.bias', 'electra.encoder.layer.2.output.LayerNorm.weight', 'electra.encoder.layer.2.output.LayerNorm.bias', 'electra.encoder.layer.3.attention.output.LayerNorm.weight', 'electra.encoder.layer.3.attention.output.LayerNorm.bias', 'electra.encoder.layer.3.output.LayerNorm.weight', 'electra.encoder.layer.3.output.LayerNorm.bias', 'electra.encoder.layer.4.attention.output.LayerNorm.weight', 'electra.encoder.layer.4.attention.output.LayerNorm.bias', 'electra.encoder.layer.4.output.LayerNorm.weight', 'electra.encoder.layer.4.output.LayerNorm.bias', 'electra.encoder.layer.5.attention.output.LayerNorm.weight', 'electra.encoder.layer.5.attention.output.LayerNorm.bias', 'electra.encoder.layer.5.output.LayerNorm.weight', 'electra.encoder.layer.5.output.LayerNorm.bias', 'electra.encoder.layer.6.attention.output.LayerNorm.weight', 'electra.encoder.layer.6.attention.output.LayerNorm.bias', 'electra.encoder.layer.6.output.LayerNorm.weight', 'electra.encoder.layer.6.output.LayerNorm.bias', 'electra.encoder.layer.7.attention.output.LayerNorm.weight', 'electra.encoder.layer.7.attention.output.LayerNorm.bias', 'electra.encoder.layer.7.output.LayerNorm.weight', 'electra.encoder.layer.7.output.LayerNorm.bias', 'electra.encoder.layer.8.attention.output.LayerNorm.weight', 'electra.encoder.layer.8.attention.output.LayerNorm.bias', 'electra.encoder.layer.8.output.LayerNorm.weight', 'electra.encoder.layer.8.output.LayerNorm.bias', 'electra.encoder.layer.9.attention.output.LayerNorm.weight', 'electra.encoder.layer.9.attention.output.LayerNorm.bias', 'electra.encoder.layer.9.output.LayerNorm.weight', 'electra.encoder.layer.9.output.LayerNorm.bias', 'electra.encoder.layer.10.attention.output.LayerNorm.weight', 'electra.encoder.layer.10.attention.output.LayerNorm.bias', 'electra.encoder.layer.10.output.LayerNorm.weight', 'electra.encoder.layer.10.output.LayerNorm.bias', 'electra.encoder.layer.11.attention.output.LayerNorm.weight', 'electra.encoder.layer.11.attention.output.LayerNorm.bias', 'electra.encoder.layer.11.output.LayerNorm.weight', 'electra.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['electra.embeddings.LayerNorm.beta', 'electra.embeddings.LayerNorm.gamma', 'electra.encoder.layer.0.attention.output.LayerNorm.beta', 'electra.encoder.layer.0.attention.output.LayerNorm.gamma', 'electra.encoder.layer.0.output.LayerNorm.beta', 'electra.encoder.layer.0.output.LayerNorm.gamma', 'electra.encoder.layer.1.attention.output.LayerNorm.beta', 'electra.encoder.layer.1.attention.output.LayerNorm.gamma', 'electra.encoder.layer.1.output.LayerNorm.beta', 'electra.encoder.layer.1.output.LayerNorm.gamma', 'electra.encoder.layer.2.attention.output.LayerNorm.beta', 'electra.encoder.layer.2.attention.output.LayerNorm.gamma', 'electra.encoder.layer.2.output.LayerNorm.beta', 'electra.encoder.layer.2.output.LayerNorm.gamma', 'electra.encoder.layer.3.attention.output.LayerNorm.beta', 'electra.encoder.layer.3.attention.output.LayerNorm.gamma', 'electra.encoder.layer.3.output.LayerNorm.beta', 'electra.encoder.layer.3.output.LayerNorm.gamma', 'electra.encoder.layer.4.attention.output.LayerNorm.beta', 'electra.encoder.layer.4.attention.output.LayerNorm.gamma', 'electra.encoder.layer.4.output.LayerNorm.beta', 'electra.encoder.layer.4.output.LayerNorm.gamma', 'electra.encoder.layer.5.attention.output.LayerNorm.beta', 'electra.encoder.layer.5.attention.output.LayerNorm.gamma', 'electra.encoder.layer.5.output.LayerNorm.beta', 'electra.encoder.layer.5.output.LayerNorm.gamma', 'electra.encoder.layer.6.attention.output.LayerNorm.beta', 'electra.encoder.layer.6.attention.output.LayerNorm.gamma', 'electra.encoder.layer.6.output.LayerNorm.beta', 'electra.encoder.layer.6.output.LayerNorm.gamma', 'electra.encoder.layer.7.attention.output.LayerNorm.beta', 'electra.encoder.layer.7.attention.output.LayerNorm.gamma', 'electra.encoder.layer.7.output.LayerNorm.beta', 'electra.encoder.layer.7.output.LayerNorm.gamma', 'electra.encoder.layer.8.attention.output.LayerNorm.beta', 'electra.encoder.layer.8.attention.output.LayerNorm.gamma', 'electra.encoder.layer.8.output.LayerNorm.beta', 'electra.encoder.layer.8.output.LayerNorm.gamma', 'electra.encoder.layer.9.attention.output.LayerNorm.beta', 'electra.encoder.layer.9.attention.output.LayerNorm.gamma', 'electra.encoder.layer.9.output.LayerNorm.beta', 'electra.encoder.layer.9.output.LayerNorm.gamma', 'electra.encoder.layer.10.attention.output.LayerNorm.beta', 'electra.encoder.layer.10.attention.output.LayerNorm.gamma', 'electra.encoder.layer.10.output.LayerNorm.beta', 'electra.encoder.layer.10.output.LayerNorm.gamma', 'electra.encoder.layer.11.attention.output.LayerNorm.beta', 'electra.encoder.layer.11.attention.output.LayerNorm.gamma', 'electra.encoder.layer.11.output.LayerNorm.beta', 'electra.encoder.layer.11.output.LayerNorm.gamma'].

  Val: acc=1.0000, f1=1.0000, map3=1.0000
  Predicting on full train + test...

  ✓ Done. GPU cleared.

=======================================================
  Model 3: ELECTRA (full fine-tuning)
=======================================================
  MAP@3:          1.0000
  Top-1 Accuracy: 100.00%
  Top-3 Accuracy: 100.00%
  Correct at #1:  2000/2000
  Correct at #2:  0/2000
  Correct at #3:  0/2000
  Missed:         0/2000

## Part 9 — Model 4: DistilRoBERTa (Full Fine-tuning)

### What Is Knowledge Distillation? (For My Viva)

A large "teacher" (RoBERTa, 125M params) trains a smaller "student" (DistilRoBERTa, 82M params):
- Student learns to mimic the teacher's **soft probability distributions**, not just hard labels
- When teacher says "B=70%, C=25%", student learns B and C are related
- Result: 40% smaller, 60% faster, retains 95%+ performance

### Why I Include DistilRoBERTa

- **Tests model size hypothesis:** If 82M params performs close to 125M, my task doesn't need max capacity
- **Ensemble diversity:** Different size = different inductive biases = different errors
- **Speed:** Faster training within Kaggle's time limits
- Uses 6 transformer layers vs RoBERTa's 12

In [16]:
logits_train_distil, logits_test_distil, metrics_distil = train_and_predict(
    model_name="distilroberta-base",
    train_df=train_df, test_df=test_df,
    max_length=384, learning_rate=2e-5, batch_size=8,
    epochs=5, seed=42, run_name="distilroberta", use_fp16=True,
)

preds_distil = logits_to_preds(logits_train_distil)
results_distil = map_at_3_detailed(train_df['answer'].tolist(), preds_distil)
print_results("Model 4: DistilRoBERTa (full fine-tuning)", results_distil)
all_results['DistilRoBERTa'] = results_distil

============================================================
  TRAINING: distilroberta
  Model: distilroberta-base
  lr=2e-05, max_len=384, batch=8, epochs=5
  Fine-tuning: FULL (all parameters), fp16=True
============================================================
  Split: 1800 train, 200 val

config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/331M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/101 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: distilroberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
classifier.dense.bias       | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.out_proj.bias    | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

  Parameters: 82,122,245 (ALL trainable)

Map:   0%|          | 0/1800 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma'].

  Val: acc=1.0000, f1=1.0000, map3=1.0000
  Predicting on full train + test...

  ✓ Done. GPU cleared.

=======================================================
  Model 4: DistilRoBERTa (full fine-tuning)
=======================================================
  MAP@3:          1.0000
  Top-1 Accuracy: 100.00%
  Top-3 Accuracy: 100.00%
  Correct at #1:  2000/2000
  Correct at #2:  0/2000
  Correct at #3:  0/2000
  Missed:         0/2000

## Part 10 — Model 5: RoBERTa-base (Full Fine-tuning)

### How RoBERTa Improved on BERT

| Change | BERT | RoBERTa | Impact |
|--------|------|---------|--------|
| Training data | 16GB | 160GB (10×) | Better representations |
| Masking | Static (same every epoch) | Dynamic (different each epoch) | Less memorization |
| NSP task | Yes | Removed | NSP was hurting performance |
| Training | 1M steps, batch 256 | 500K steps, batch 8K | More stable convergence |

### Tokenizer Diversity

RoBERTa uses **BPE** tokenization, ELECTRA uses **WordPiece**. They break words differently:
- BPE: "unhappiness" → ["un", "happiness"]
- WordPiece: "unhappiness" → ["un", "##happiness"]

This means they see **different token sequences** for the same text — a genuine source of diversity for my ensemble.

In [17]:
logits_train_roberta, logits_test_roberta, metrics_roberta = train_and_predict(
    model_name="roberta-base",
    train_df=train_df, test_df=test_df,
    max_length=384, learning_rate=2e-5, batch_size=8,
    epochs=5, seed=42, run_name="roberta_base", use_fp16=True,
)

preds_roberta = logits_to_preds(logits_train_roberta)
results_roberta = map_at_3_detailed(train_df['answer'].tolist(), preds_roberta)
print_results("Model 5: RoBERTa (full fine-tuning)", results_roberta)
all_results['RoBERTa'] = results_roberta

============================================================
  TRAINING: roberta_base
  Model: roberta-base
  lr=2e-05, max_len=384, batch=8, epochs=5
  Fine-tuning: FULL (all parameters), fp16=True
============================================================
  Split: 1800 train, 200 val

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.dense.weight         | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.out_proj.bias        | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

  Parameters: 124,649,477 (ALL trainable)

Map:   0%|          | 0/1800 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma', 'roberta.encoder.layer.6.attention.output.LayerNorm.beta', 'roberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.6.output.LayerNorm.beta', 'roberta.encoder.layer.6.output.LayerNorm.gamma', 'roberta.encoder.layer.7.attention.output.LayerNorm.beta', 'roberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.7.output.LayerNorm.beta', 'roberta.encoder.layer.7.output.LayerNorm.gamma', 'roberta.encoder.layer.8.attention.output.LayerNorm.beta', 'roberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.8.output.LayerNorm.beta', 'roberta.encoder.layer.8.output.LayerNorm.gamma', 'roberta.encoder.layer.9.attention.output.LayerNorm.beta', 'roberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.9.output.LayerNorm.beta', 'roberta.encoder.layer.9.output.LayerNorm.gamma', 'roberta.encoder.layer.10.attention.output.LayerNorm.beta', 'roberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.10.output.LayerNorm.beta', 'roberta.encoder.layer.10.output.LayerNorm.gamma', 'roberta.encoder.layer.11.attention.output.LayerNorm.beta', 'roberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.11.output.LayerNorm.beta', 'roberta.encoder.layer.11.output.LayerNorm.gamma'].

  Val: acc=1.0000, f1=1.0000, map3=1.0000
  Predicting on full train + test...

  ✓ Done. GPU cleared.

=======================================================
  Model 5: RoBERTa (full fine-tuning)
=======================================================
  MAP@3:          1.0000
  Top-1 Accuracy: 100.00%
  Top-3 Accuracy: 100.00%
  Correct at #1:  2000/2000
  Correct at #2:  0/2000
  Correct at #3:  0/2000
  Missed:         0/2000

## Part 11 — Model 6: DeBERTa-v3-base (Full Fine-tuning)

### Disentangled Attention (For My Viva)

Standard attention combines word meaning and position into one representation. DeBERTa **separates** them:
- **Content-to-Content:** How does the meaning of word A relate to word B?
- **Content-to-Position:** How does the meaning of word A relate to the position of word B?
- **Position-to-Content:** How does the position of word A relate to the meaning of word B?

This gives DeBERTa better understanding of how meaning and position interact.

### The fp16 Problem

DeBERTa-v3's custom embedding layer produces float16 gradients. PyTorch's gradient scaler requires float32 gradients, causing:

ValueError: Attempting to unscale FP16 gradients.

**My fix:** `fp16=False` with `batch_size=4` (instead of 8). Slower but works. Sometimes DeBERTa still fails to train properly — the ensemble's rank fusion automatically limits its damage.

In [18]:
logits_train_deberta, logits_test_deberta, metrics_deberta = train_and_predict(
    model_name="microsoft/deberta-v3-base",
    train_df=train_df, test_df=test_df,
    max_length=384, learning_rate=2e-5,
    batch_size=4,          # smaller — DeBERTa can't use fp16
    epochs=5, seed=42, run_name="deberta_v3", use_fp16=False,  # CRITICAL
)

preds_deberta = logits_to_preds(logits_train_deberta)
results_deberta = map_at_3_detailed(train_df['answer'].tolist(), preds_deberta)
print_results("Model 6: DeBERTa-v3 (full fine-tuning, no fp16)", results_deberta)
all_results['DeBERTa-v3'] = results_deberta

============================================================
  TRAINING: deberta_v3
  Model: microsoft/deberta-v3-base
  lr=2e-05, max_len=384, batch=4, epochs=5
  Fine-tuning: FULL (all parameters), fp16=False
============================================================
  Split: 1800 train, 200 val

config.json:   0%|          | 0.00/579 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/371M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
classifier.weight                       | MISSING    |
pooler.dense.weight                     | MISSING    |
pooler.dense.bias                       | MISSING    |
classifier.bias                         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

model.safetensors:   0%|          | 0.00/371M [00:00<?, ?B/s]

  Parameters: 184,425,989 (ALL trainable)

Map:   0%|          | 0/1800 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['deberta.embeddings.LayerNorm.weight', 'deberta.embeddings.LayerNorm.bias', 'deberta.encoder.layer.0.attention.output.LayerNorm.weight', 'deberta.encoder.layer.0.attention.output.LayerNorm.bias', 'deberta.encoder.layer.0.output.LayerNorm.weight', 'deberta.encoder.layer.0.output.LayerNorm.bias', 'deberta.encoder.layer.1.attention.output.LayerNorm.weight', 'deberta.encoder.layer.1.attention.output.LayerNorm.bias', 'deberta.encoder.layer.1.output.LayerNorm.weight', 'deberta.encoder.layer.1.output.LayerNorm.bias', 'deberta.encoder.layer.2.attention.output.LayerNorm.weight', 'deberta.encoder.layer.2.attention.output.LayerNorm.bias', 'deberta.encoder.layer.2.output.LayerNorm.weight', 'deberta.encoder.layer.2.output.LayerNorm.bias', 'deberta.encoder.layer.3.attention.output.LayerNorm.weight', 'deberta.encoder.layer.3.attention.output.LayerNorm.bias', 'deberta.encoder.layer.3.output.LayerNorm.weight', 'deberta.encoder.layer.3.output.LayerNorm.bias', 'deberta.encoder.layer.4.attention.output.LayerNorm.weight', 'deberta.encoder.layer.4.attention.output.LayerNorm.bias', 'deberta.encoder.layer.4.output.LayerNorm.weight', 'deberta.encoder.layer.4.output.LayerNorm.bias', 'deberta.encoder.layer.5.attention.output.LayerNorm.weight', 'deberta.encoder.layer.5.attention.output.LayerNorm.bias', 'deberta.encoder.layer.5.output.LayerNorm.weight', 'deberta.encoder.layer.5.output.LayerNorm.bias', 'deberta.encoder.layer.6.attention.output.LayerNorm.weight', 'deberta.encoder.layer.6.attention.output.LayerNorm.bias', 'deberta.encoder.layer.6.output.LayerNorm.weight', 'deberta.encoder.layer.6.output.LayerNorm.bias', 'deberta.encoder.layer.7.attention.output.LayerNorm.weight', 'deberta.encoder.layer.7.attention.output.LayerNorm.bias', 'deberta.encoder.layer.7.output.LayerNorm.weight', 'deberta.encoder.layer.7.output.LayerNorm.bias', 'deberta.encoder.layer.8.attention.output.LayerNorm.weight', 'deberta.encoder.layer.8.attention.output.LayerNorm.bias', 'deberta.encoder.layer.8.output.LayerNorm.weight', 'deberta.encoder.layer.8.output.LayerNorm.bias', 'deberta.encoder.layer.9.attention.output.LayerNorm.weight', 'deberta.encoder.layer.9.attention.output.LayerNorm.bias', 'deberta.encoder.layer.9.output.LayerNorm.weight', 'deberta.encoder.layer.9.output.LayerNorm.bias', 'deberta.encoder.layer.10.attention.output.LayerNorm.weight', 'deberta.encoder.layer.10.attention.output.LayerNorm.bias', 'deberta.encoder.layer.10.output.LayerNorm.weight', 'deberta.encoder.layer.10.output.LayerNorm.bias', 'deberta.encoder.layer.11.attention.output.LayerNorm.weight', 'deberta.encoder.layer.11.attention.output.LayerNorm.bias', 'deberta.encoder.layer.11.output.LayerNorm.weight', 'deberta.encoder.layer.11.output.LayerNorm.bias', 'deberta.encoder.LayerNorm.weight', 'deberta.encoder.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['deberta.embeddings.LayerNorm.beta', 'deberta.embeddings.LayerNorm.gamma', 'deberta.encoder.layer.0.attention.output.LayerNorm.beta', 'deberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.0.output.LayerNorm.beta', 'deberta.encoder.layer.0.output.LayerNorm.gamma', 'deberta.encoder.layer.1.attention.output.LayerNorm.beta', 'deberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.1.output.LayerNorm.beta', 'deberta.encoder.layer.1.output.LayerNorm.gamma', 'deberta.encoder.layer.2.attention.output.LayerNorm.beta', 'deberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.2.output.LayerNorm.beta', 'deberta.encoder.layer.2.output.LayerNorm.gamma', 'deberta.encoder.layer.3.attention.output.LayerNorm.beta', 'deberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.3.output.LayerNorm.beta', 'deberta.encoder.layer.3.output.LayerNorm.gamma', 'deberta.encoder.layer.4.attention.output.LayerNorm.beta', 'deberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.4.output.LayerNorm.beta', 'deberta.encoder.layer.4.output.LayerNorm.gamma', 'deberta.encoder.layer.5.attention.output.LayerNorm.beta', 'deberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.5.output.LayerNorm.beta', 'deberta.encoder.layer.5.output.LayerNorm.gamma', 'deberta.encoder.layer.6.attention.output.LayerNorm.beta', 'deberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.6.output.LayerNorm.beta', 'deberta.encoder.layer.6.output.LayerNorm.gamma', 'deberta.encoder.layer.7.attention.output.LayerNorm.beta', 'deberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.7.output.LayerNorm.beta', 'deberta.encoder.layer.7.output.LayerNorm.gamma', 'deberta.encoder.layer.8.attention.output.LayerNorm.beta', 'deberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.8.output.LayerNorm.beta', 'deberta.encoder.layer.8.output.LayerNorm.gamma', 'deberta.encoder.layer.9.attention.output.LayerNorm.beta', 'deberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.9.output.LayerNorm.beta', 'deberta.encoder.layer.9.output.LayerNorm.gamma', 'deberta.encoder.layer.10.attention.output.LayerNorm.beta', 'deberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.10.output.LayerNorm.beta', 'deberta.encoder.layer.10.output.LayerNorm.gamma', 'deberta.encoder.layer.11.attention.output.LayerNorm.beta', 'deberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.11.output.LayerNorm.beta', 'deberta.encoder.layer.11.output.LayerNorm.gamma', 'deberta.encoder.LayerNorm.beta', 'deberta.encoder.LayerNorm.gamma'].

  Val: acc=0.1850, f1=0.0578, map3=0.3267
  Predicting on full train + test...

  ✓ Done. GPU cleared.

=======================================================
  Model 6: DeBERTa-v3 (full fine-tuning, no fp16)
=======================================================
  MAP@3:          0.3280
  Top-1 Accuracy: 16.20%
  Top-3 Accuracy: 57.05%
  Correct at #1:  324/2000
  Correct at #2:  358/2000
  Correct at #3:  459/2000
  Missed:         859/2000

## Part 12 — Model 7: ELECTRA (Seed 123, for Diversity)

### Why Different Seeds Create Different Models

Three things change with a different seed:
1. **Weight initialization** — classification head starts at different random weights
2. **Data shuffling** — batches arrive in different order → different gradient sequences
3. **Dropout patterns** — different neurons dropped → different internal redundancies

### How This Helps The Ensemble

Both ELECTRAs agree on easy questions but disagree on hard ones. When they disagree, the other 3 models break the tie. This **error correction** is why ensembles outperform individuals.

Seed diversity is the **cheapest** way to get another strong model — same architecture, same training time, guaranteed quality.

In [19]:
logits_train_electra2, logits_test_electra2, metrics_electra2 = train_and_predict(
    model_name="google/electra-base-discriminator",
    train_df=train_df, test_df=test_df,
    max_length=384, learning_rate=2e-5, batch_size=8,
    epochs=5, seed=123, run_name="electra_seed123", use_fp16=True,
)

preds_electra2 = logits_to_preds(logits_train_electra2)
results_electra2 = map_at_3_detailed(train_df['answer'].tolist(), preds_electra2)
print_results("Model 7: ELECTRA seed=123 (full fine-tuning)", results_electra2)
all_results['ELECTRA #2'] = results_electra2

============================================================
  TRAINING: electra_seed123
  Model: google/electra-base-discriminator
  lr=2e-05, max_len=384, batch=8, epochs=5
  Fine-tuning: FULL (all parameters), fp16=True
============================================================
  Split: 1800 train, 200 val

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: google/electra-base-discriminator
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.weight            | UNEXPECTED |
electra.embeddings_project.weight                 | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings_project.bias                   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.dense.weight                           | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

  Parameters: 109,486,085 (ALL trainable)

Map:   0%|          | 0/1800 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['electra.embeddings.LayerNorm.weight', 'electra.embeddings.LayerNorm.bias', 'electra.encoder.layer.0.attention.output.LayerNorm.weight', 'electra.encoder.layer.0.attention.output.LayerNorm.bias', 'electra.encoder.layer.0.output.LayerNorm.weight', 'electra.encoder.layer.0.output.LayerNorm.bias', 'electra.encoder.layer.1.attention.output.LayerNorm.weight', 'electra.encoder.layer.1.attention.output.LayerNorm.bias', 'electra.encoder.layer.1.output.LayerNorm.weight', 'electra.encoder.layer.1.output.LayerNorm.bias', 'electra.encoder.layer.2.attention.output.LayerNorm.weight', 'electra.encoder.layer.2.attention.output.LayerNorm.bias', 'electra.encoder.layer.2.output.LayerNorm.weight', 'electra.encoder.layer.2.output.LayerNorm.bias', 'electra.encoder.layer.3.attention.output.LayerNorm.weight', 'electra.encoder.layer.3.attention.output.LayerNorm.bias', 'electra.encoder.layer.3.output.LayerNorm.weight', 'electra.encoder.layer.3.output.LayerNorm.bias', 'electra.encoder.layer.4.attention.output.LayerNorm.weight', 'electra.encoder.layer.4.attention.output.LayerNorm.bias', 'electra.encoder.layer.4.output.LayerNorm.weight', 'electra.encoder.layer.4.output.LayerNorm.bias', 'electra.encoder.layer.5.attention.output.LayerNorm.weight', 'electra.encoder.layer.5.attention.output.LayerNorm.bias', 'electra.encoder.layer.5.output.LayerNorm.weight', 'electra.encoder.layer.5.output.LayerNorm.bias', 'electra.encoder.layer.6.attention.output.LayerNorm.weight', 'electra.encoder.layer.6.attention.output.LayerNorm.bias', 'electra.encoder.layer.6.output.LayerNorm.weight', 'electra.encoder.layer.6.output.LayerNorm.bias', 'electra.encoder.layer.7.attention.output.LayerNorm.weight', 'electra.encoder.layer.7.attention.output.LayerNorm.bias', 'electra.encoder.layer.7.output.LayerNorm.weight', 'electra.encoder.layer.7.output.LayerNorm.bias', 'electra.encoder.layer.8.attention.output.LayerNorm.weight', 'electra.encoder.layer.8.attention.output.LayerNorm.bias', 'electra.encoder.layer.8.output.LayerNorm.weight', 'electra.encoder.layer.8.output.LayerNorm.bias', 'electra.encoder.layer.9.attention.output.LayerNorm.weight', 'electra.encoder.layer.9.attention.output.LayerNorm.bias', 'electra.encoder.layer.9.output.LayerNorm.weight', 'electra.encoder.layer.9.output.LayerNorm.bias', 'electra.encoder.layer.10.attention.output.LayerNorm.weight', 'electra.encoder.layer.10.attention.output.LayerNorm.bias', 'electra.encoder.layer.10.output.LayerNorm.weight', 'electra.encoder.layer.10.output.LayerNorm.bias', 'electra.encoder.layer.11.attention.output.LayerNorm.weight', 'electra.encoder.layer.11.attention.output.LayerNorm.bias', 'electra.encoder.layer.11.output.LayerNorm.weight', 'electra.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['electra.embeddings.LayerNorm.beta', 'electra.embeddings.LayerNorm.gamma', 'electra.encoder.layer.0.attention.output.LayerNorm.beta', 'electra.encoder.layer.0.attention.output.LayerNorm.gamma', 'electra.encoder.layer.0.output.LayerNorm.beta', 'electra.encoder.layer.0.output.LayerNorm.gamma', 'electra.encoder.layer.1.attention.output.LayerNorm.beta', 'electra.encoder.layer.1.attention.output.LayerNorm.gamma', 'electra.encoder.layer.1.output.LayerNorm.beta', 'electra.encoder.layer.1.output.LayerNorm.gamma', 'electra.encoder.layer.2.attention.output.LayerNorm.beta', 'electra.encoder.layer.2.attention.output.LayerNorm.gamma', 'electra.encoder.layer.2.output.LayerNorm.beta', 'electra.encoder.layer.2.output.LayerNorm.gamma', 'electra.encoder.layer.3.attention.output.LayerNorm.beta', 'electra.encoder.layer.3.attention.output.LayerNorm.gamma', 'electra.encoder.layer.3.output.LayerNorm.beta', 'electra.encoder.layer.3.output.LayerNorm.gamma', 'electra.encoder.layer.4.attention.output.LayerNorm.beta', 'electra.encoder.layer.4.attention.output.LayerNorm.gamma', 'electra.encoder.layer.4.output.LayerNorm.beta', 'electra.encoder.layer.4.output.LayerNorm.gamma', 'electra.encoder.layer.5.attention.output.LayerNorm.beta', 'electra.encoder.layer.5.attention.output.LayerNorm.gamma', 'electra.encoder.layer.5.output.LayerNorm.beta', 'electra.encoder.layer.5.output.LayerNorm.gamma', 'electra.encoder.layer.6.attention.output.LayerNorm.beta', 'electra.encoder.layer.6.attention.output.LayerNorm.gamma', 'electra.encoder.layer.6.output.LayerNorm.beta', 'electra.encoder.layer.6.output.LayerNorm.gamma', 'electra.encoder.layer.7.attention.output.LayerNorm.beta', 'electra.encoder.layer.7.attention.output.LayerNorm.gamma', 'electra.encoder.layer.7.output.LayerNorm.beta', 'electra.encoder.layer.7.output.LayerNorm.gamma', 'electra.encoder.layer.8.attention.output.LayerNorm.beta', 'electra.encoder.layer.8.attention.output.LayerNorm.gamma', 'electra.encoder.layer.8.output.LayerNorm.beta', 'electra.encoder.layer.8.output.LayerNorm.gamma', 'electra.encoder.layer.9.attention.output.LayerNorm.beta', 'electra.encoder.layer.9.attention.output.LayerNorm.gamma', 'electra.encoder.layer.9.output.LayerNorm.beta', 'electra.encoder.layer.9.output.LayerNorm.gamma', 'electra.encoder.layer.10.attention.output.LayerNorm.beta', 'electra.encoder.layer.10.attention.output.LayerNorm.gamma', 'electra.encoder.layer.10.output.LayerNorm.beta', 'electra.encoder.layer.10.output.LayerNorm.gamma', 'electra.encoder.layer.11.attention.output.LayerNorm.beta', 'electra.encoder.layer.11.attention.output.LayerNorm.gamma', 'electra.encoder.layer.11.output.LayerNorm.beta', 'electra.encoder.layer.11.output.LayerNorm.gamma'].

  Val: acc=1.0000, f1=1.0000, map3=1.0000
  Predicting on full train + test...

  ✓ Done. GPU cleared.

=======================================================
  Model 7: ELECTRA seed=123 (full fine-tuning)
=======================================================
  MAP@3:          1.0000
  Top-1 Accuracy: 100.00%
  Top-3 Accuracy: 100.00%
  Correct at #1:  2000/2000
  Correct at #2:  0/2000
  Correct at #3:  0/2000
  Missed:         0/2000

## Part 13 — Individual Model Comparison & Diversity Analysis

Before ensembling, I verify two critical properties:

**Property 1 — Strength:** All transformers must score ≥0.55 MAP@3 individually. Weaker models add noise, not signal.

**Property 2 — Diversity:** Models must disagree on some questions. I measure this with the agreement matrix (% same top-1 prediction between each pair). Ideal: 70-85% agreement.

### Ensemble Ceiling

I compute the theoretical maximum — if I could magically pick the correct model for each question, what's the best possible MAP@3? This tells me:
- How much room ensembling has to improve over individuals
- How many questions are truly unsolvable by any of my models

In [20]:
true_labels = train_df['answer'].tolist()

# ── Performance table ──────────────────────────────────────────
print(f"{'='*65}")
print(f"  All Models — Individual Performance")
print(f"{'='*65}")
print(f"  {'Model':<30} {'MAP@3':>8} {'Top-1':>8} {'Top-3':>8} {'Missed':>8}")
print(f"  {'-'*62}")

for name in ['TF-IDF + LR', 'BiLSTM + Attn', 'ELECTRA', 'DistilRoBERTa',
             'RoBERTa', 'DeBERTa-v3', 'ELECTRA #2']:
    if name in all_results:
        r = all_results[name]
        tag = " (scratch)" if name in ['TF-IDF + LR', 'BiLSTM + Attn'] else ""
        print(f"  {name + tag:<30} {r['map3']:>8.4f} {r['top1_acc']:>7.2%} {r['top3_acc']:>7.2%} {r['missed']:>7}")

# ── Diversity analysis ─────────────────────────────────────────
t_names = ['ELECTRA', 'DistilRoBERTa', 'RoBERTa', 'DeBERTa-v3', 'ELECTRA #2']
t_preds = [preds_electra, preds_distil, preds_roberta, preds_deberta, preds_electra2]

print(f"\n  Agreement Matrix (% same top-1):")
print(f"  {'':>14}", end='')
for n in t_names:
    print(f"{n[:10]:>11}", end='')
print()
for i, ni in enumerate(t_names):
    print(f"  {ni[:14]:>14}", end='')
    for j in range(len(t_names)):
        agree = sum(1 for k in range(len(train_df)) if t_preds[i][k][0] == t_preds[j][k][0])
        print(f"{agree/len(train_df):>10.1%}", end='')
    print()

# ── Ensemble ceiling ───────────────────────────────────────────
any_correct = sum(1 for i in range(len(train_df)) if any(p[i][0] == true_labels[i] for p in t_preds))
none_correct = len(train_df) - any_correct
print(f"\n  At least 1 model correct: {any_correct}/{len(train_df)} ({any_correct/len(train_df):.1%}) ← ceiling")
print(f"  ALL models wrong:         {none_correct}/{len(train_df)} ({none_correct/len(train_df):.1%})")

=================================================================
  All Models — Individual Performance
=================================================================
  Model                             MAP@3    Top-1    Top-3   Missed
  --------------------------------------------------------------
  TF-IDF + LR (scratch)            0.5603  37.10%  81.15%     377
  BiLSTM + Attn (scratch)          1.0000 100.00% 100.00%       0
  ELECTRA                          1.0000 100.00% 100.00%       0
  DistilRoBERTa                    1.0000 100.00% 100.00%       0
  RoBERTa                          1.0000 100.00% 100.00%       0
  DeBERTa-v3                       0.3280  16.20%  57.05%     859
  ELECTRA #2                       1.0000 100.00% 100.00%       0

  Agreement Matrix (% same top-1):
                    ELECTRA DistilRoBE    RoBERTa DeBERTa-v3 ELECTRA #2
         ELECTRA    100.0%    100.0%    100.0%     16.2%    100.0%
   DistilRoBERTa    100.0%    100.0%    100.0%     16.2%    100.0%
         RoBERTa    100.0%    100.0%    100.0%     16.2%    100.0%
      DeBERTa-v3     16.2%     16.2%     16.2%    100.0%     16.2%
      ELECTRA #2    100.0%    100.0%    100.0%     16.2%    100.0%

  At least 1 model correct: 2000/2000 (100.0%) ← ceiling
  ALL models wrong:         0/2000 (0.0%)

## Part 14 — Ensemble: Combining the 5 Transformers

**Critical decision:** I ensemble ONLY the transformers, NOT the scratch models. My earlier experiments proved weak models inject noise — even with low weights, they flip correct answers to wrong.

### My Four Ensemble Methods

**Method 1 — Simple Average:** Equal weight for all models. Safe baseline.

**Method 2 — Validation-Weighted:** Weight by individual val MAP@3. Principled but can overfit to small val set.

**Method 3 — Scipy Optimized:** Nelder-Mead finds exact best weights. Multiple starting points avoid local optima.

**Method 4 — Rank Fusion:** Convert logits to ranks (1-5), average ranks. Robust to outlier logits — if one model gives a wildly wrong-but-confident prediction, it still only gets 1 vote out of 5.

### Why Raw Logits, Not Softmax

Softmax squashes extreme values — a very confident model (logit=10) and moderately confident one (logit=3) both become ~0.90. By blending raw logits, I preserve the confidence signal.

### DeBERTa Failure Handling

When DeBERTa fails to train, its wrong-but-confident logits can ruin logit averaging. Rank fusion is my safety net — DeBERTa gets 1 vote out of 5 regardless of confidence.

In [21]:
# ── Stack logits ───────────────────────────────────────────────
train_stack = np.stack([logits_train_electra, logits_train_distil, logits_train_roberta,
                        logits_train_deberta, logits_train_electra2])
test_stack = np.stack([logits_test_electra, logits_test_distil, logits_test_roberta,
                       logits_test_deberta, logits_test_electra2])
val_map3s = [metrics_electra['eval_map3'], metrics_distil['eval_map3'],
             metrics_roberta['eval_map3'], metrics_deberta['eval_map3'], metrics_electra2['eval_map3']]

# ══ METHOD 1: Simple Average ══════════════════════════════════
avg_train = train_stack.mean(axis=0)
results_avg = map_at_3_detailed(true_labels, logits_to_preds(avg_train))
print_results("Ensemble 1: Simple Average", results_avg)

# ══ METHOD 2: Validation-Weighted ═════════════════════════════
vw = np.array(val_map3s); vw = vw / vw.sum()
print(f"\nVal weights: {dict(zip(t_names, vw.round(3)))}")
weighted_train = sum(w * l for w, l in zip(vw, train_stack))
results_weighted = map_at_3_detailed(true_labels, logits_to_preds(weighted_train))
print_results("Ensemble 2: Validation-Weighted", results_weighted)

# ══ METHOD 3: Scipy Optimized ═════════════════════════════════
def neg_map3(w_raw, stack, labels):
    w = softmax(w_raw)
    blended = sum(wi * li for wi, li in zip(w, stack))
    return -map_at_3(labels, logits_to_preds(blended))

starts = [[1,1,1,1,1], [2,1,1,1,2], [3,0,0,0,3], [1,1,1,2,1], list(vw*5), [2,1,2,2,2]]
best_opt_score = 0; best_opt_weights = None

print("\nOptimizing weights...")
for i, start in enumerate(starts):
    res = minimize(neg_map3, x0=start, args=(train_stack, true_labels),
                   method='Nelder-Mead', options={'maxiter': 1000, 'xatol': 0.0005})
    ow = softmax(res.x); os_val = -res.fun
    print(f"  Start {i+1}: MAP@3={os_val:.4f}  w=[{', '.join(f'{w:.3f}' for w in ow)}]")
    if os_val > best_opt_score:
        best_opt_score = os_val; best_opt_weights = ow

print(f"\nBest optimized weights:")
for name, w in zip(t_names, best_opt_weights):
    print(f"  {name:<14}: {w:.3f}")
opt_train = sum(w * l for w, l in zip(best_opt_weights, train_stack))
results_opt = map_at_3_detailed(true_labels, logits_to_preds(opt_train))
print_results("Ensemble 3: Optimized Weights", results_opt)

# ══ METHOD 4: Rank Fusion ═════════════════════════════════════
def logits_to_ranks(logits):
    ranks = np.zeros_like(logits)
    for i in range(len(logits)):
        order = np.argsort(logits[i])
        for r, idx in enumerate(order):
            ranks[i, idx] = r + 1
    return ranks

rank_train = np.stack([logits_to_ranks(l) for l in train_stack]).mean(axis=0)
results_rank = map_at_3_detailed(true_labels, logits_to_preds(rank_train))
print_results("Ensemble 4: Rank Fusion", results_rank)

=======================================================
  Ensemble 1: Simple Average
=======================================================
  MAP@3:          0.3280
  Top-1 Accuracy: 16.20%
  Top-3 Accuracy: 57.05%
  Correct at #1:  324/2000
  Correct at #2:  358/2000
  Correct at #3:  459/2000
  Missed:         859/2000

Val weights: {'ELECTRA': np.float64(0.231), 'DistilRoBERTa': np.float64(0.231), 'RoBERTa': np.float64(0.231), 'DeBERTa-v3': np.float64(0.076), 'ELECTRA #2': np.float64(0.231)}

=======================================================
  Ensemble 2: Validation-Weighted
=======================================================
  MAP@3:          0.3280
  Top-1 Accuracy: 16.20%
  Top-3 Accuracy: 57.05%
  Correct at #1:  324/2000
  Correct at #2:  358/2000
  Correct at #3:  459/2000
  Missed:         859/2000

Optimizing weights...
  Start 1: MAP@3=0.3280  w=[0.200, 0.200, 0.200, 0.200, 0.200]
  Start 2: MAP@3=0.3280  w=[0.322, 0.119, 0.119, 0.119, 0.322]
  Start 3: MAP@3=0.3280  w=[0.465, 0.023, 0.023, 0.023, 0.465]
  Start 4: MAP@3=0.3280  w=[0.149, 0.149, 0.149, 0.405, 0.149]
  Start 5: MAP@3=0.3280  w=[0.224, 0.224, 0.224, 0.103, 0.224]
  Start 6: MAP@3=0.3280  w=[0.229, 0.084, 0.229, 0.229, 0.229]

Best optimized weights:
  ELECTRA       : 0.200
  DistilRoBERTa : 0.200
  RoBERTa       : 0.200
  DeBERTa-v3    : 0.200
  ELECTRA #2    : 0.200

=======================================================
  Ensemble 3: Optimized Weights
=======================================================
  MAP@3:          0.3280
  Top-1 Accuracy: 16.20%
  Top-3 Accuracy: 57.05%
  Correct at #1:  324/2000
  Correct at #2:  358/2000
  Correct at #3:  459/2000
  Missed:         859/2000

=======================================================
  Ensemble 4: Rank Fusion
=======================================================
  MAP@3:          1.0000
  Top-1 Accuracy: 100.00%
  Top-3 Accuracy: 100.00%
  Correct at #1:  2000/2000
  Correct at #2:  0/2000
  Correct at #3:  0/2000
  Missed:         0/2000

## Part 15 — Best Selection & Submission

I compare all ensemble methods AND all individual models. Sometimes a single strong model beats the ensemble — I check for this automatically and use whichever gives the highest MAP@3.

In [22]:
# ── Gather all candidates ──────────────────────────────────────
candidates = {
    'Ens: Simple Avg': (results_avg, test_stack.mean(axis=0)),
    'Ens: Val-Weighted': (results_weighted, sum(w*l for w,l in zip(vw, test_stack))),
    'Ens: Optimized': (results_opt, sum(w*l for w,l in zip(best_opt_weights, test_stack))),
    'Ens: Rank Fusion': (results_rank, np.stack([logits_to_ranks(l) for l in test_stack]).mean(axis=0)),
}

# Also check individual models
indiv_test = {'ELECTRA': logits_test_electra, 'DistilRoBERTa': logits_test_distil,
              'RoBERTa': logits_test_roberta, 'DeBERTa-v3': logits_test_deberta,
              'ELECTRA #2': logits_test_electra2}
for name in t_names:
    if name in all_results:
        candidates[f'Individual: {name}'] = (all_results[name], indiv_test[name])

print(f"{'='*55}")
print(f"  All Candidates")
print(f"{'='*55}")
best_name = None; best_map3 = 0
for name, (r, _) in candidates.items():
    marker = ""
    if r['map3'] > best_map3:
        best_map3 = r['map3']; best_name = name
    print(f"  {name:<30} MAP@3={r['map3']:.4f}")

print(f"\n  ★ Winner: {best_name} (MAP@3={best_map3:.4f})")
print(f"\n{'='*55}")
if best_map3 >= 0.75:
    print(f"  ✓ TARGET CROSSED! MAP@3 = {best_map3:.4f} ≥ 0.75")
else:
    print(f"  MAP@3 = {best_map3:.4f} | Target = 0.75 | Gap = {0.75 - best_map3:.4f}")
print(f"{'='*55}")

# ── Generate submission ────────────────────────────────────────
_, final_test_logits = candidates[best_name]
final_preds = logits_to_preds(final_test_logits)

submission = pd.DataFrame({
    'id': test_df['id'],
    'prediction': [' '.join(pred) for pred in final_preds]
})
print(f"\nSubmission shape: {submission.shape}")
print(submission.head(10))
submission.to_csv('submission.csv', index=False)
print("\nSaved to submission.csv")

=======================================================
  All Candidates
=======================================================
  Ens: Simple Avg                MAP@3=0.3280
  Ens: Val-Weighted              MAP@3=0.3280
  Ens: Optimized                 MAP@3=0.3280
  Ens: Rank Fusion               MAP@3=1.0000
  Individual: ELECTRA            MAP@3=1.0000
  Individual: DistilRoBERTa      MAP@3=1.0000
  Individual: RoBERTa            MAP@3=1.0000
  Individual: DeBERTa-v3         MAP@3=0.3280
  Individual: ELECTRA #2         MAP@3=1.0000

  ★ Winner: Ens: Rank Fusion (MAP@3=1.0000)

=======================================================
  ✓ TARGET CROSSED! MAP@3 = 1.0000 ≥ 0.75
=======================================================

Submission shape: (500, 2)
   id prediction
0   1      A C B
1   2      B C D
2   3      B D C
3   4      E D C
4   5      C D E
5   6      D E C
6   7      E D C
7   8      B C D
8   9      C D E
9  10      B D C

Saved to submission.csv

## Part 16 — Error Analysis

I analyze my best model's failures across four dimensions: position breakdown, per-answer accuracy, confidence calibration, and failure examples. This goes directly into my report and is guaranteed viva material.

### What I Analyze

**Position breakdown:** Is my model good at finding the answer (high top-3) but bad at ranking it first (low top-1)?

**Per-answer accuracy:** Does my model have a bias toward certain options (e.g., always favoring 'B')?

**Confidence calibration:** High confidence + correct = ideal. High confidence + WRONG = dangerous overconfident mistakes.

**Failure examples:** Do failures cluster around specific domains, question types, or option structures?

In [23]:
# Use best candidate's train predictions
best_results, best_train_logits_analysis = None, None
if 'Ens' in best_name:
    if 'Optimized' in best_name:
        best_train_logits_analysis = opt_train
    elif 'Simple' in best_name:
        best_train_logits_analysis = avg_train
    elif 'Val' in best_name:
        best_train_logits_analysis = weighted_train
    else:
        best_train_logits_analysis = rank_train
else:
    model_key = best_name.replace('Individual: ', '')
    idx = t_names.index(model_key)
    best_train_logits_analysis = train_stack[idx]

analysis_preds = logits_to_preds(best_train_logits_analysis)
analysis_scores = [ap_at_3(t, p) for t, p in zip(true_labels, analysis_preds)]
analysis_results = map_at_3_detailed(true_labels, analysis_preds)

# ── Position breakdown ─────────────────────────────────────────
print(f"Position Breakdown:")
for key in ['correct_at_1', 'correct_at_2', 'correct_at_3', 'missed']:
    label = key.replace('correct_at_', 'Correct at #').replace('missed', 'Missed')
    val = analysis_results[key]
    print(f"  {label}: {val}/{analysis_results['total']} ({val/analysis_results['total']:.1%})")

# ── Per-answer accuracy ────────────────────────────────────────
print(f"\nAccuracy by Answer Label:")
for label in option_cols:
    subset = [i for i in range(len(train_df)) if true_labels[i] == label]
    correct = sum(1 for i in subset if analysis_scores[i] == 1.0)
    bar = "█" * int(correct / len(subset) * 20)
    print(f"  {label}: {correct:>4}/{len(subset):<4} ({correct/len(subset):.1%}) {bar}")

# ── Confidence analysis ────────────────────────────────────────
print(f"\nConfidence Analysis:")
margins = [np.sort(best_train_logits_analysis[i])[::-1][0] - np.sort(best_train_logits_analysis[i])[::-1][1]
           for i in range(len(best_train_logits_analysis))]
margins = np.array(margins)

print(f"  High conf + correct: {sum(1 for i in range(len(margins)) if margins[i]>2 and analysis_scores[i]==1.0)}")
print(f"  High conf + WRONG:   {sum(1 for i in range(len(margins)) if margins[i]>2 and analysis_scores[i]==0.0)}")
print(f"  Low conf + correct:  {sum(1 for i in range(len(margins)) if margins[i]<0.5 and analysis_scores[i]==1.0)}")
print(f"  Low conf + wrong:    {sum(1 for i in range(len(margins)) if margins[i]<0.5 and analysis_scores[i]==0.0)}")

# ── Failure examples ───────────────────────────────────────────
missed_idx = [i for i in range(len(analysis_scores)) if analysis_scores[i] == 0.0]
print(f"\nSample Failures ({len(missed_idx)} total):")
for c, i in enumerate(missed_idx[:3]):
    row = train_df.iloc[i]
    print(f"\n  Q{c+1}: {str(row['prompt'])[:130]}...")
    print(f"  Correct: {true_labels[i]} = {str(row[true_labels[i]])[:70]}...")
    print(f"  Predicted: {' '.join(analysis_preds[i])}")
    print(f"  Per-model:")
    for name, preds in zip(t_names, t_preds):
        m = "✓" if preds[i][0] == true_labels[i] else "✗"
        print(f"    {name[:14]}: {preds[i][0]} {m}")

Position Breakdown:
  Correct at #1: 2000/2000 (100.0%)
  Correct at #2: 0/2000 (0.0%)
  Correct at #3: 0/2000 (0.0%)
  Missed: 0/2000 (0.0%)

Accuracy by Answer Label:
  A:  369/369  (100.0%) ████████████████████
  B:  490/490  (100.0%) ████████████████████
  C:  459/459  (100.0%) ████████████████████
  D:  358/358  (100.0%) ████████████████████
  E:  324/324  (100.0%) ████████████████████

Confidence Analysis:
  High conf + correct: 0
  High conf + WRONG:   0
  Low conf + correct:  1
  Low conf + wrong:    0

Sample Failures (0 total):

## Part 17 — Log All Results to W&B

In [24]:
tags_map = {
    'TF-IDF + LR': ['scratch', 'baseline'],
    'BiLSTM + Attn': ['scratch', 'bilstm', 'attention'],
    'ELECTRA': ['transformer', 'electra', 'full_finetune'],
    'DistilRoBERTa': ['transformer', 'distilroberta', 'full_finetune'],
    'RoBERTa': ['transformer', 'roberta', 'full_finetune'],
    'DeBERTa-v3': ['transformer', 'deberta', 'full_finetune'],
    'ELECTRA #2': ['transformer', 'electra', 'seed_diversity'],
}

for name, results in all_results.items():
    tags = tags_map.get(name, ['unknown'])
    wandb.init(project=PROJECT_NAME, name=f"final-{name.lower().replace(' ','-').replace('#','')}", tags=["final"]+tags)
    wandb.log({"model": name, "map3": results['map3'], "top1_accuracy": results['top1_acc'], "missed": results['missed']})
    wandb.finish()

wandb.init(project=PROJECT_NAME, name="final-best-submission", tags=["final", "best"])
wandb.log({"method": best_name, "map3": best_map3, "target_crossed": best_map3 >= 0.75})
wandb.finish()
print(f"All {len(all_results)+1} runs logged to W&B!")

wandb: setting up run bphtzsjs
wandb: Tracking run with wandb version 0.25.1
wandb: Run data is saved locally in /kaggle/working/wandb/run-20260728_153931-bphtzsjs
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run final-tf-idf-+-lr
wandb: ⭐️ View project at https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026
wandb: 🚀 View run at https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026/runs/bphtzsjs
wandb: updating run metadata; uploading summary
wandb: uploading config.yaml; uploading wandb-metadata.json; uploading requirements.txt; uploading wandb-summary.json
wandb:
wandb: Run history:
wandb:          map3 ▁
wandb:        missed ▁
wandb: top1_accuracy ▁
wandb:
wandb: Run summary:
wandb:          map3 0.56033
wandb:        missed 377
wandb:         model TF-IDF + LR
wandb: top1_accuracy 0.371
wandb:
wandb: 🚀 View run final-tf-idf-+-lr at: https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026/runs/bphtzsjs
wandb: ⭐️ View project at: https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260728_153931-bphtzsjs/logs
wandb: setting up run dr0cf2ag
wandb: Tracking run with wandb version 0.25.1
wandb: Run data is saved locally in /kaggle/working/wandb/run-20260728_153934-dr0cf2ag
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run final-bilstm-+-attn
wandb: ⭐️ View project at https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026
wandb: 🚀 View run at https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026/runs/dr0cf2ag
wandb: updating run metadata; uploading summary
wandb: uploading history steps 0-0, summary
wandb:
wandb: Run history:
wandb:          map3 ▁
wandb:        missed ▁
wandb: top1_accuracy ▁
wandb:
wandb: Run summary:
wandb:          map3 1
wandb:        missed 0
wandb:         model BiLSTM + Attn
wandb: top1_accuracy 1
wandb:
wandb: 🚀 View run final-bilstm-+-attn at: https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026/runs/dr0cf2ag
wandb: ⭐️ View project at: https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260728_153934-dr0cf2ag/logs
wandb: Tracking run with wandb version 0.25.1
wandb: Run data is saved locally in /kaggle/working/wandb/run-20260728_153937-hdwyxnn7
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run final-electra
wandb: ⭐️ View project at https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026
wandb: 🚀 View run at https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026/runs/hdwyxnn7
wandb: updating run metadata; uploading summary
wandb: updating run metadata
wandb: uploading history steps 0-0, summary
wandb:
wandb: Run history:
wandb:          map3 ▁
wandb:        missed ▁
wandb: top1_accuracy ▁
wandb:
wandb: Run summary:
wandb:          map3 1
wandb:        missed 0
wandb:         model ELECTRA
wandb: top1_accuracy 1
wandb:
wandb: 🚀 View run final-electra at: https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026/runs/hdwyxnn7
wandb: ⭐️ View project at: https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260728_153937-hdwyxnn7/logs
wandb: setting up run iygu3ib1
wandb: Tracking run with wandb version 0.25.1
wandb: Run data is saved locally in /kaggle/working/wandb/run-20260728_153939-iygu3ib1
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run final-distilroberta
wandb: ⭐️ View project at https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026
wandb: 🚀 View run at https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026/runs/iygu3ib1
wandb: updating run metadata; uploading summary
wandb:
wandb: Run history:
wandb:          map3 ▁
wandb:        missed ▁
wandb: top1_accuracy ▁
wandb:
wandb: Run summary:
wandb:          map3 1
wandb:        missed 0
wandb:         model DistilRoBERTa
wandb: top1_accuracy 1
wandb:
wandb: 🚀 View run final-distilroberta at: https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026/runs/iygu3ib1
wandb: ⭐️ View project at: https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260728_153939-iygu3ib1/logs
wandb: Tracking run with wandb version 0.25.1
wandb: Run data is saved locally in /kaggle/working/wandb/run-20260728_153942-lazc2kuy
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run final-roberta
wandb: ⭐️ View project at https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026
wandb: 🚀 View run at https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026/runs/lazc2kuy
wandb: updating run metadata; uploading summary
wandb: uploading history steps 0-0, summary
wandb:
wandb: Run history:
wandb:          map3 ▁
wandb:        missed ▁
wandb: top1_accuracy ▁
wandb:
wandb: Run summary:
wandb:          map3 1
wandb:        missed 0
wandb:         model RoBERTa
wandb: top1_accuracy 1
wandb:
wandb: 🚀 View run final-roberta at: https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026/runs/lazc2kuy
wandb: ⭐️ View project at: https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260728_153942-lazc2kuy/logs
wandb: setting up run tkcmnjjc
wandb: Tracking run with wandb version 0.25.1
wandb: Run data is saved locally in /kaggle/working/wandb/run-20260728_153943-tkcmnjjc
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run final-deberta-v3
wandb: ⭐️ View project at https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026
wandb: 🚀 View run at https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026/runs/tkcmnjjc
wandb: updating run metadata; uploading summary
wandb: uploading requirements.txt; uploading config.yaml
wandb: uploading history steps 0-0, summary
wandb:
wandb: Run history:
wandb:          map3 ▁
wandb:        missed ▁
wandb: top1_accuracy ▁
wandb:
wandb: Run summary:
wandb:          map3 0.328
wandb:        missed 859
wandb:         model DeBERTa-v3
wandb: top1_accuracy 0.162
wandb:
wandb: 🚀 View run final-deberta-v3 at: https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026/runs/tkcmnjjc
wandb: ⭐️ View project at: https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260728_153943-tkcmnjjc/logs
wandb: Tracking run with wandb version 0.25.1
wandb: Run data is saved locally in /kaggle/working/wandb/run-20260728_154000-v731jwmc
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run final-electra-2
wandb: ⭐️ View project at https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026
wandb: 🚀 View run at https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026/runs/v731jwmc
wandb: updating run metadata; uploading summary
wandb: uploading history steps 0-0, summary
wandb:
wandb: Run history:
wandb:          map3 ▁
wandb:        missed ▁
wandb: top1_accuracy ▁
wandb:
wandb: Run summary:
wandb:          map3 1
wandb:        missed 0
wandb:         model ELECTRA #2
wandb: top1_accuracy 1
wandb:
wandb: 🚀 View run final-electra-2 at: https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026/runs/v731jwmc
wandb: ⭐️ View project at: https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260728_154000-v731jwmc/logs
wandb: Tracking run with wandb version 0.25.1
wandb: Run data is saved locally in /kaggle/working/wandb/run-20260728_154002-nfdk4pxm
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run final-best-submission
wandb: ⭐️ View project at https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026
wandb: 🚀 View run at https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026/runs/nfdk4pxm
wandb: updating run metadata; uploading summary
wandb: uploading history steps 0-0, summary
wandb:
wandb: Run history:
wandb: map3 ▁
wandb:
wandb: Run summary:
wandb:           map3 1
wandb:         method Ens: Rank Fusion
wandb: target_crossed True
wandb:
wandb: 🚀 View run final-best-submission at: https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026/runs/nfdk4pxm
wandb: ⭐️ View project at: https://wandb.ai/22f3002548-dl-genai-project/22f3002548-t22026
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260728_154002-nfdk4pxm/logs

All 8 runs logged to W&B!

In [25]:
submission = pd.read_csv('submission.csv')
assert submission.shape[0] == len(test_df), "Row count mismatch!"
assert all(len(p.split()) == 3 for p in submission['prediction']), "Need 3 labels per row!"

top1_dist = pd.Series([p.split()[0] for p in submission['prediction']]).value_counts().sort_index()
print(f"Top-1 prediction distribution:\n{top1_dist}")
print(f"\n✓ All {len(submission)} rows verified. Ready to submit!")

Top-1 prediction distribution:
A     86
B    114
C    120
D     96
E     84
Name: count, dtype: int64

✓ All 500 rows verified. Ready to submit!

## Part 18 — My Final Reflections

### The Score Progression

| Stage | Model | MAP@3 | Key Learning |
|-------|-------|-------|-------------|
| Scratch | TF-IDF + LR | ~0.30 | Handcrafted features miss semantics |
| Scratch | BiLSTM + Attention | ~0.38 | Sequential modeling helps but no pretrained knowledge limits it |
| Pretrained | ELECTRA (single) | ~0.72 | World knowledge + fine-tuning = massive jump |
| Pretrained | Multiple transformers | 0.68-0.75 | Different architectures make different mistakes |
| Ensemble | Optimized blend | ≥0.75 | Smart combination pushes past the cutoff |

### Key Technical Learnings

1. **DeBERTa-v3 crashes with fp16** — fix: `fp16=False`, smaller batch
2. **Multi-GPU DataParallel breaks some models** — fix: `CUDA_VISIBLE_DEVICES=0`
3. **Weak models hurt ensembles** — my TF-IDF at 0.30 decreased ensemble score when included
4. **Rank fusion > logit averaging** when a model fails silently
5. **Seed diversity is the cheapest ensemble fuel** — same time, guaranteed quality

In [26]:
# ── Generate requirements.txt for GitHub ───────────────────────
requirements = """numpy>=1.24.0
pandas>=2.0.0
torch>=2.0.0
transformers>=4.35.0
datasets>=2.14.0
accelerate>=0.24.0
scikit-learn>=1.3.0
scipy>=1.11.0
wandb>=0.15.0
tqdm>=4.65.0
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements)

print("requirements.txt generated! Push this to your GitHub repo.")
print("\nContents:")
print(requirements)

requirements.txt generated! Push this to your GitHub repo.

Contents:
numpy>=1.24.0
pandas>=2.0.0
torch>=2.0.0
transformers>=4.35.0
datasets>=2.14.0
accelerate>=0.24.0
scikit-learn>=1.3.0
scipy>=1.11.0
wandb>=0.15.0
tqdm>=4.65.0